// Content for every tool sheet. One object per sheet, same fields on each,
// so every sheet reads the same way. Copy follows lib/mindprint-source-of-
// truth.md section 2: no "personality", "strength/weakness", "brain",
// "dominant"; commas instead of em dashes; WHY-WHAT style notation.
//
// shots: first is the hero (large), the rest sit side by side below it.
//   file  = PNG in shots/ (without extension)
//   crop  = [x, y, w] fractions of the image to zoom into (default whole width, from the top)
//   ai    = true when the screenshot needs a real AI result (next session)
// group: profile | teams | career | resources (sets the header color)

module.exports = [
  {
    slug: 'mindprint-profile', group: 'profile', name: 'MindPrint™ Profile',
    promise: 'See where each person does their best thinking, and what quietly drains them.',
    serves: ['Every employee', 'Managers', 'New hires', 'Coaches'],
    problem: 'People describe how they work in vague terms, and managers are left guessing. Good people end up spending their days on work that drains them, and nobody can name why a capable team keeps stalling.',
    benefits: [
      ['A clear map of energy', 'Primary, secondary, and tertiary orientation show where someone is fueled, functional, and depleted under problem-solving pressure.'],
      ['A shared language', 'Every profile uses the same WHY, WHAT, and HOW vocabulary, so teams can talk about how they think without it getting personal.'],
      ['Practical next steps', 'How to work with them, where they add the most value, and who they collaborate best with.'],
    ],
    how: ['Answer 23 forced-choice questions, about 7 to 10 minutes', 'The profile appears in the portal right away', 'Download the full profile as a PDF to share'],
    outputs: ['One of six profiles, such as WHY-WHAT', 'What energizes and what drains them', 'How to work with them', 'Roles where they thrive and best collaborators'],
    extra: ['Not a personality test', 'MindPrint™ maps cognitive orientation under problem-solving pressure. It measures energy, not ability, and skills in all three orientations can be learned.'],
    pairs: ['Communication Field Guide', 'AI & Delegation Guide', 'Team Dynamics'],
    shots: [
      { file: 'profile-1-hero', crop: [0, 0, 0.75], caption: 'Each person sees their profile the moment they finish.' },
      { file: 'profile-3-body', crop: [0, 0.38, 0.52], caption: 'Who they are, what energizes them, and what drains them.' },
      { file: 'profile-2-value', crop: [0, 0, 0.6], caption: 'Where they add the most value and the roles where they thrive.' },
    ],
  },
  {
    slug: 'communication-field-guide', group: 'profile', name: 'Communication Field Guide',
    promise: 'Write in a way people wired differently actually hear.',
    serves: ['Every employee', 'Leaders who write to large audiences', 'Cross-functional teams'],
    problem: 'A message that makes perfect sense to its writer can land as vague, rushed, or buried in detail for a reader wired differently. The gap is predictable, but nobody sees it in their own writing.',
    benefits: [
      ['See your own signature', 'What your writing always includes and what it conspicuously leaves out.'],
      ['Know how it lands', 'How WHY, WHAT, and HOW readers each hear the same message.'],
      ['Three adjustments', 'The specific changes that buy the most understanding for the least effort.'],
    ],
    how: ['Linked from each person\'s profile', 'One guide for each of the six profiles', 'Read in minutes, use on the next message'],
    outputs: ['How you naturally write', 'Your signature: present and absent', 'How you land with each orientation', 'The three adjustments'],
    extra: ['Read it for someone else', 'The guide for a colleague\'s profile shows what they will listen for in your message before you send it.'],
    pairs: ['Orientation Translator', 'MindPrint™ Profile', 'Weekly Profile Tips'],
    shots: [
      { file: 'fieldguide-1-top', crop: [0.22, 0, 0.56], caption: 'A guide written for each profile, linked from the profile page.' },
      { file: 'fieldguide-2-land', crop: [0.23, 0, 0.54], caption: 'How WHY, WHAT, and HOW readers each hear the same message.' },
      { file: 'fieldguide-3-adjust', crop: [0.23, 0.5, 0.54], caption: 'Your signature: what your writing includes, and what it leaves out.' },
    ],
  },
  {
    slug: 'ai-delegation-guide', group: 'profile', name: 'AI & Delegation Guide',
    promise: 'Hand the work that drains you to AI, a teammate, or a partner, on purpose.',
    serves: ['Every employee', 'Managers planning workloads', 'Teams adopting AI'],
    problem: 'Everyone has work that drains them, and most people grind through it alone. AI adoption stalls because people don\'t know which of their tasks to hand off, or to whom.',
    benefits: [
      ['A routing plan', 'Each kind of draining task is marked Utilize AI, Delegate, or Collaborate, with the reason why.'],
      ['A resource for every task', 'Each row links to the matching tool in the Tertiary Support Library.'],
      ['Your own tasks, classified', 'Describe a task in your own words and get a routing recommendation for it.'],
    ],
    how: ['Opens on the person\'s own profile', 'Scan the task table for what drains them', 'Follow the linked resource or route the task'],
    outputs: ['Task routing table for the profile', 'What the drain looks like in practice', 'The partner they need', 'Universal supports for any profile'],
    extra: ['For owners', 'On team accounts, owners can view the guide for any of the six profiles to plan support for their people.'],
    pairs: ['AI Companions', 'Tertiary Support Library', 'MindPrint™ Profile'],
    shots: [
      { file: 'delegation-2-table', crop: [0, 0, 0.8], caption: 'Every draining task, routed to AI, a teammate, or collaboration, with a resource.' },
      { file: 'delegation-1-header', crop: [0, 0, 0.6], caption: 'The guide opens on the person\'s own profile.' },
      { file: 'delegation-3-classify', caption: 'Describe your own task and get a routing recommendation.', ai: true },
    ],
  },
  {
    slug: 'ai-companions', group: 'profile', name: 'AI Companions',
    promise: 'AI drafts the work that drains you, so you only have to judge it.',
    serves: ['Every employee', 'Leaders with full plates', 'Anyone stuck on tertiary work'],
    problem: 'Tertiary work still has to get done: the detailed plan, the purpose statement, the status update. Doing it from a blank page costs far more energy than reviewing a strong first draft.',
    benefits: [
      ['Precision Companion', 'HOW work: break a goal into tasks, pre-flight checklists, gap reviews, edge cases, and definitions of done.'],
      ['Purpose Companion', 'WHY work: a guided purpose brief, a North Star one-pager, so-what translations, and opening lines.'],
      ['Progress Companion', 'WHAT work: good-enough shipping criteria, milestone backplans, progress updates, and closing cards.'],
    ],
    how: ['Pick the Companion and the task', 'Fill in a short form or answer a guided interview', 'Review, refine, and copy the draft'],
    outputs: ['A draft to judge, not a finished fact', 'Follow-up refinement in plain language', 'One-click copy into your own document'],
    extra: ['Built to replace, not to teach', 'Each Companion produces the draining work for review rather than coaching someone to enjoy it, in line with the MindPrint™ energy model.'],
    pairs: ['AI & Delegation Guide', 'Tertiary Support Library', 'Orientation Translator'],
    shots: [
      { file: 'companions-1-precision', caption: 'Precision Companion: a full task breakdown from a one-line goal.', ai: true },
      { file: 'companions-2-purpose', caption: 'Purpose Companion: a guided purpose brief.', ai: true },
      { file: 'companions-3-progress', caption: 'Progress Companion: a ready-to-send progress update.', ai: true },
    ],
  },
  {
    slug: 'orientation-translator', group: 'profile', name: 'Orientation Translator',
    promise: 'The same facts, re-answered for the reader\'s signature question.',
    serves: ['Managers', 'Leaders and communicators', 'Anyone writing up or across the org'],
    problem: 'People wired differently talk past each other. A WHY reader wants the purpose, a WHAT reader wants the next step, and a HOW reader wants the detail, so one message rarely works for all three.',
    benefits: [
      ['Rewrite for any reader', 'Translate a message for a WHY, WHAT, or HOW reader, all three at once, or a specific person\'s profile.'],
      ['See what changed', 'Every rewrite ends with a short note on the moves it made and why.'],
      ['Nothing invented silently', 'Any fact the rewrite adds, like a date or an owner, is marked as proposed.'],
    ],
    how: ['Paste the message you\'re about to send', 'Choose the reader or a person\'s profile', 'Copy the rewrite, or refine it further'],
    outputs: ['A rewritten message', 'A "what changed and why" note', 'Optional: Detect (beta), a hypothesis of a writer\'s orientation from samples'],
    extra: ['Detect mode is never for hiring', 'Detect offers a hypothesis to support coaching and self-awareness. It is not used for hiring or screening decisions.'],
    pairs: ['Communication Field Guide', 'Team Dynamics', 'AI Companions'],
    shots: [
      { file: 'translator-1-result', caption: 'One message, rewritten for a HOW reader, with notes on what changed.', ai: true },
      { file: 'translator-2-detect', caption: 'Detect (beta): a hypothesis from writing samples.', ai: true },
    ],
  },
  {
    slug: 'weekly-profile-tips', group: 'profile', name: 'Weekly Profile Tips',
    promise: 'One small, specific way to work with your tertiary, every Monday.',
    serves: ['Every employee with a profile', 'Teams building new habits', 'Managers reinforcing training'],
    problem: 'Insight from an assessment fades within weeks. Without a light, regular nudge, people slide back into old habits and the profile becomes a PDF nobody opens.',
    benefits: [
      ['Keeps the profile alive', 'A short tip lands every week, long after the initial rollout.'],
      ['Specific to each person', 'Every tip is written for the person\'s own profile, never generic advice.'],
      ['Zero effort to run', 'Tips send automatically, and anyone can unsubscribe with one click.'],
    ],
    how: ['Starts automatically once a profile is complete', 'One tip each Monday, in order', 'Twenty tips per profile, never repeating'],
    outputs: ['A branded weekly email', 'A headline and one practical move', 'A 20-week sequence for each profile'],
    extra: ['Example', 'A WHY-WHAT leader\'s first tip: "Hand off the map, not just the compass." Ten minutes writing down your assumptions before every handoff.'],
    pairs: ['MindPrint™ Profile', 'Communication Field Guide', 'Tertiary Support Library'],
    shots: [
      { file: 'tips-1-email', caption: 'A real tip from the WHY-WHAT sequence.' },
      { file: 'tips-2-email', crop: [0.02, 0.08, 0.95], caption: 'From the HOW-WHY sequence.' },
      { file: 'tips-3-email', crop: [0.02, 0.08, 0.95], caption: 'From the WHAT-HOW sequence.' },
    ],
  },
  {
    slug: 'team-dynamics', group: 'teams', name: 'Team Dynamics',
    promise: 'See how your team fits together before friction costs you a quarter.',
    serves: ['Team leaders', 'HR and People partners', 'Executives and facilitators'],
    problem: 'Recurring team friction looks personal, so it gets handled as a personality clash. In reality it follows predictable orientation patterns that can be named and worked through.',
    benefits: [
      ['See the whole team', 'The mix of orientations across the roster, and each person\'s profile and tertiary.'],
      ['Name friction for what it is', 'Pick any two people to see their likely friction pattern, why it happens, and how to work through it.'],
      ['Staff the work well', 'Match people to the kind of problem in front of the team, and pair the right people on a task.'],
    ],
    how: ['Built from the account\'s real roster', 'Filter by team', 'Switch between six views'],
    outputs: ['Team Canvas and Energy Map', 'Problem Match and Collaboration pairings', 'Friction Spotter', 'Blind Spot Report: what the team is likely to miss'],
    extra: ['Six views, one roster', 'Team Canvas, Problem Match, Friction Spotter, Energy Map, Collaboration, and the Blind Spot Report all update as people complete their profiles.'],
    pairs: ['Session Architect', 'Meeting Architect', 'Team Administration'],
    shots: [
      { file: 'dynamics-3-energy', caption: 'Energy Map: what energizes and drains each person on the team.' },
      { file: 'dynamics-4-problem', crop: [0.02, 0.42, 0.62], caption: 'Problem Match: who should lead execution work.' },
      { file: 'dynamics-2-friction', crop: [0, 0, 0.55], caption: 'Friction Spotter: a named pattern and how to work through it.' },
    ],
  },
  {
    slug: 'session-architect', group: 'teams', name: 'Session Architect',
    promise: 'Design workshops that use every kind of thinker in the room.',
    serves: ['Facilitators', 'Team leaders', 'HR, L&D, and consultants'],
    problem: 'Most sessions run on one kind of energy. Brainstorms lose the detail people, planning meetings lose the purpose people, and the room leaves with a pile of ideas nobody owns.',
    benefits: [
      ['Sequenced on purpose', 'Every session moves through WHY, WHAT, and HOW, so each orientation gets its moment.'],
      ['Runnable, not theoretical', 'Each block comes with a specific activity, steps, facilitator tips, and how you\'ll know it worked.'],
      ['Built for this room', 'Suggested openers, breakout groups, and watch-fors are based on who is actually attending.'],
    ],
    how: ['Add attendees by profile, or pull in the team roster', 'Choose the session type and length', 'Build the session, then download the materials'],
    outputs: ['A timed agenda with suggested openers', 'Activity sheets and breakout groups', 'Room watch-fors for every attendee', 'Slide deck, facilitator guide, participant handout, activity cards'],
    extra: ['Four session types', 'Brainstorm, decision-making, planning or kickoff, and retrospective, in 60 or 90 minutes, a half day, or a full day.'],
    pairs: ['Team Dynamics', 'Meeting Architect', 'Tertiary Support Library'],
    shots: [
      { file: 'session-1-agenda', crop: [0, 0, 0.7], caption: 'A timed agenda sequenced through WHY, WHAT, and HOW, with openers.' },
      { file: 'session-2-activity', crop: [0, 0.47, 0.6], caption: 'An activity sheet for every block.' },
      { file: 'session-3-roles', crop: [0, 0, 0.5], caption: 'Room watch-fors for every attendee.' },
    ],
  },
  {
    slug: 'meeting-architect', group: 'teams', name: 'Meeting Architect',
    promise: 'Fix the recurring meetings that run long or go nowhere.',
    serves: ['Managers', 'Team leads', 'Executives and chiefs of staff'],
    problem: 'Recurring meetings drift. Status meetings turn into problem-solving, 1:1s turn into status, and leaders don\'t notice where their own orientation is shaping the meeting.',
    benefits: [
      ['A meeting with a job', 'A clear purpose, what can move to async, and a timed structure you can run next week.'],
      ['Designed around your challenges', 'Built from what you need the meeting to do and what is going wrong today.'],
      ['Know where to lean in', 'Where your own profile helps the meeting, and where to get help.'],
    ],
    how: ['Pick the meeting type and length', 'Add objectives, challenges, and who attends', 'Get the redesign and download it as a PDF'],
    outputs: ['Purpose and async or live split', 'A timed live agenda', 'Role assignments for attendees', 'Signs the meeting is working, or failing'],
    extra: ['Seven meeting types', 'Weekly status, team meeting, leadership update, 1:1, performance or career conversation, all-hands, and client check-in.'],
    pairs: ['Session Architect', 'Team Dynamics', 'Orientation Translator'],
    shots: [
      { file: 'meeting-1-result', caption: 'A redesigned weekly status meeting, timed and assigned.', ai: true },
      { file: 'meeting-2-form', crop: [0, 0, 0.6], caption: 'Start from the meeting type, objectives, and challenges.' },
      { file: 'meeting-3-leanin', caption: 'Where the leader should lean in, and where to get help.', ai: true },
    ],
  },
  {
    slug: 'onboarding-resources', group: 'teams', name: 'Onboarding Resources',
    promise: 'A first 90 days built around how the new hire is wired.',
    serves: ['Hiring managers', 'HR and People teams', 'New hires'],
    problem: 'Onboarding plans treat every new hire the same. Early wins depend on the right kind of work and support, and a mismatch in the first weeks is easy to misread as a poor hire.',
    benefits: [
      ['Two sides of one plan', 'A Manager Integration Guide and a New Hire Brief for each of the six profiles.'],
      ['The first weeks, done right', 'What energizes and drains them early, plus Day 1 and Week 1 essentials.'],
      ['Check-ins that matter', 'What to look for at 30, 60, and 90 days, and the misreadings to avoid.'],
    ],
    how: ['Choose the new hire\'s profile', 'Switch between the manager and new hire views', 'Download either guide as a PDF'],
    outputs: ['Energizing early on, and draining if unmanaged', 'Day 1 and Week 1, done right', '30, 60, and 90-day check-ins', 'Best-fit onboarding partner and common misreadings'],
    extra: ['Ready the day they start', 'Works before the new hire has an account. Pick the profile from their assessment results and share the brief.'],
    pairs: ['Team Dynamics', 'MindPrint™ Profile', 'Team Administration'],
    shots: [
      { file: 'onboarding-1-manager', crop: [0, 0, 0.85], caption: 'The Manager Integration Guide for a HOW-WHAT hire.' },
      { file: 'onboarding-2-checkins', crop: [0, 0, 0.6], caption: 'What to check at 30, 60, and 90 days.' },
      { file: 'onboarding-3-newhire', crop: [0, 0.05, 0.5], caption: 'The New Hire Brief, written to the new hire.' },
    ],
  },
  {
    slug: 'role-alignment-analyzer', group: 'career', name: 'Role Alignment Analyzer',
    promise: 'See how well a role fits the way someone thinks, before they take it.',
    serves: ['Individuals weighing a move', 'Managers and HR', 'Career coaches'],
    problem: 'Role decisions focus on skills and experience, and miss whether the day-to-day work will energize or drain the person. A great hire in the wrong-shaped role burns out quietly.',
    benefits: [
      ['An alignment score', 'How the role\'s demands line up with the person\'s primary, secondary, and tertiary orientation.'],
      ['Energize and drain, specifically', 'What will fuel them in this exact role, and what will cost them.'],
      ['A plan to make it work', 'Concrete recommendations and the partner profiles that complete the fit.'],
    ],
    how: ['Enter any role title', 'Get a scored analysis for the profile', 'Revisit past analyses any time'],
    outputs: ['Alignment score with rationale', 'What will energize and what will drain', 'Recommendations and partner types', 'A saved history of analyses'],
    extra: ['Explainable scores', 'Scores use a fixed MindPrint™ formula applied to the role\'s WHY, WHAT, and HOW demands, so every score comes with its reasoning.'],
    pairs: ['Job Description Analyzer', 'Career Guidance Tool', 'MindPrint™ Profile'],
    shots: [
      { file: 'fit-1-result', caption: 'An alignment score and rationale for a specific role.', ai: true },
      { file: 'fit-2-detail', caption: 'What will energize, what will drain, and how to make it work.', ai: true },
    ],
  },
  {
    slug: 'job-description-analyzer', group: 'career', name: 'Job Description Analyzer',
    promise: 'Find out what a role really demands, and which profiles it fits.',
    serves: ['Hiring managers', 'HR and talent teams', 'Job seekers'],
    problem: 'Job descriptions list skills, but not the kind of thinking the work demands every day. Teams write roles that nobody can sustain, and candidates can\'t tell what they\'re signing up for.',
    benefits: [
      ['The cognitive demand split', 'How much of the role is WHY, WHAT, and HOW work.'],
      ['All six profiles, ranked', 'How each profile lines up against the role, and why.'],
      ['Better role design', 'Spot a role that asks for everything at once before it goes live.'],
    ],
    how: ['Paste a job description or enter a URL', 'Analyze the role', 'Review the breakdown and the ranking'],
    outputs: ['WHY, WHAT, and HOW demand breakdown', 'Ranked fit for all six profiles', 'Profile-by-profile detail'],
    extra: ['For role design', 'Use it to understand and write roles. MindPrint™ describes energy, not ability, and is not used to screen candidates out.'],
    pairs: ['Role Alignment Analyzer', 'Career Guidance Tool', 'Onboarding Resources'],
    shots: [
      { file: 'jd-1-result', caption: 'The demand breakdown and ranked fit for all six profiles.', ai: true },
      { file: 'jd-2-form', crop: [0.12, 0.25, 0.6], caption: 'Paste a job description or enter a URL.' },
    ],
  },
  {
    slug: 'career-guidance-tool', group: 'career', name: 'Career Guidance Tool',
    promise: 'Find a role that energizes you.',
    serves: ['Individuals planning a next move', 'Career coaches', 'University career services'],
    problem: 'Career advice rarely accounts for how a person is wired to solve problems. People chase titles and end up in work that drains them, without understanding why.',
    benefits: [
      ['Best-fit roles', 'Specific roles that match the person\'s profile, career level, and track.'],
      ['Energizers and challenges', 'What will fuel them and what to plan around in those roles.'],
      ['Folds in what they know', 'Adds DiSC, CliftonStrengths, or MBTI results for a more personalized report.'],
    ],
    how: ['Choose career level, track, and industry', 'Add priorities and other assessment results', 'Get a personalized report and download it'],
    outputs: ['Best-fit roles with reasons', 'What will energize and challenge them', 'Strategies specific to how they think', 'A PDF report'],
    extra: ['Works alongside other tools', 'MindPrint™ is the organizing framework. Other assessments refine the report and never override the profile.'],
    pairs: ['Role Alignment Analyzer', 'Job Description Analyzer', 'MindPrint™ Profile'],
    shots: [
      { file: 'career-1-result', caption: 'A personalized career report with best-fit roles.', ai: true },
      { file: 'career-2-form', crop: [0.02, 0.38, 0.6], caption: 'Inputs include career level, track, and other assessments.' },
    ],
  },
  {
    slug: 'tertiary-support-library', group: 'resources', name: 'Tertiary Support Library',
    promise: '43 practical tools that make draining work cheaper.',
    serves: ['Every employee', 'Managers and coaches', 'Teams'],
    problem: 'Telling someone to "get better at details" or "think bigger" doesn\'t work. Draining work needs structure, rituals, and partners, not more willpower.',
    benefits: [
      ['Four approaches', 'Scaffold, Teach, Support, and Replace: each resource lowers the cost of the drain in a specific way.'],
      ['Organized by need', 'Collections for a tertiary HOW, WHAT, or WHY, plus universal and team resources.'],
      ['Ready to use', 'Resources come with downloadable templates to use right away.'],
    ],
    how: ['Browse by the orientation a resource supports', 'Open a resource page', 'Download the template and use it'],
    outputs: ['The drain it addresses', 'What the tool does and how to use it', 'What it won\'t do', 'A template, and what pairs well with it'],
    extra: ['None of them ask anyone to enjoy draining work', 'They make it cheaper, which is the honest promise of the MindPrint™ energy model.'],
    pairs: ['AI & Delegation Guide', 'AI Companions', 'Weekly Profile Tips'],
    shots: [
      { file: 'library-1-index', crop: [0, 0, 0.85], caption: 'Resources organized by the orientation they support.' },
      { file: 'library-2-resource', crop: [0.23, 0, 0.54], caption: 'Each resource explains the drain and how the tool helps.' },
    ],
  },
  {
    slug: 'curio-assistant', group: 'resources', name: 'Curio Assistant',
    promise: 'Describe what you\'re working on. Curio points you to the right tool.',
    serves: ['Every employee', 'New users of the platform', 'Busy managers'],
    problem: 'With many tools and resources, people don\'t know where to start, so they use one or two and miss the rest.',
    benefits: [
      ['Plain-language help', 'Ask about a challenge, a task, or MindPrint™ itself.'],
      ['Grounded answers only', 'Answers come only from Curio\'s MindPrint™ materials, nothing made up.'],
      ['Request what you don\'t have', 'Locked tools can be requested in one click.'],
    ],
    how: ['Open Ask Curio from any page', 'Describe the challenge', 'Open the recommended tool or resource'],
    outputs: ['Recommended tools, resources, and articles', 'Short answers to MindPrint™ questions', 'One-click access requests'],
    extra: ['Always on hand', 'The Ask Curio button sits in the corner of every portal page.'],
    pairs: ['Tertiary Support Library', 'AI & Delegation Guide', 'Insights'],
    shots: [
      { file: 'assistant-1-answer', caption: 'Ask about a real challenge and get pointed to the right tools.', ai: true },
      { file: 'assistant-2-start', caption: 'Suggested starting questions.', ai: true },
    ],
  },
  {
    slug: 'insights', group: 'resources', name: 'Insights',
    promise: 'Fresh thinking on talent, teams, and what it means to think differently.',
    serves: ['Leaders and managers', 'HR and People teams', 'Every employee'],
    problem: 'Frameworks fade when they live only in a one-time workshop. Teams need ongoing ideas that connect the framework to the work in front of them.',
    benefits: [
      ['Ideas in context', 'Articles connect MindPrint™ to real situations: hiring, meetings, leadership, and change.'],
      ['Inside the platform', 'Read right where the tools are, no separate site to visit.'],
      ['Easy to share', 'Every article has its own link to pass along.'],
    ],
    how: ['Open Recent Articles from the sidebar', 'Browse the latest articles', 'Read in the portal or share the link'],
    outputs: ['Curio articles and perspectives', 'New articles as they are published'],
    extra: ['Published by Curio', 'New articles appear in the portal as soon as they are published.'],
    pairs: ['Curio Assistant', 'Weekly Profile Tips', 'MindPrint™ Profile'],
    shots: [
      { file: 'insights-1-index', caption: 'Recent articles, inside the portal.', sanity: true },
      { file: 'insights-2-article', caption: 'A full article view.', sanity: true },
    ],
  },
  {
    slug: 'team-administration', group: 'resources', name: 'Team Administration',
    promise: 'Roll MindPrint™ out to a whole team, and see the results in one place.',
    serves: ['HR and People teams', 'Account owners', 'Team managers'],
    problem: 'Rolling out an assessment usually means spreadsheets, chasing links, and results scattered across inboxes.',
    benefits: [
      ['Send in minutes', 'Send assessment links to one person or a batch, with a customizable email.'],
      ['Clear status', 'See which links are available, sent, and completed.'],
      ['Team-level insight', 'Profile and orientation charts, a results table, and lists by profile.'],
    ],
    how: ['Send assessment links', 'Track completion as people finish', 'Organize people into teams with managers'],
    outputs: ['Team roster with profiles and roles', 'Assessment link tracking', 'Analytics charts and a results table', 'Lists of everyone with a given profile'],
    extra: ['Managers see their own team', 'Owners see everything. A manager sees and acts only on their own team.'],
    pairs: ['Team Dynamics', 'Onboarding Resources', 'Session Architect'],
    shots: [
      { file: 'admin-3-analytics', crop: [0, 0, 0.85], caption: 'Analytics: profiles and primary orientations across the team.' },
      { file: 'admin-1-team', crop: [0.05, 0.5, 0.6], caption: 'The team roster, with roles, teams, and profiles.' },
      { file: 'admin-2-send', crop: [0.12, 0.3, 0.6], caption: 'Send assessment links to one person or a batch.' },
    ],
  },
];
