# Collections C (tertiary WHY), D (universal), E (teams & meetings)

TOOLS_CDE = [

dict(num=21, collection="C", mode="Scaffold", title="The Five-Question Purpose Brief",
lead="A ten-minute structured brief, completed once before any significant piece of work begins. <b>It generates the purpose thinking that would otherwise cost you real energy</b>, and captures it in a form you can reference for the life of the project instead of regenerating it every time someone asks.",
drain="When your energy lives in progress and precision, articulating purpose is draining work. The instinct is to skip it and start executing, and that instinct has a cost: rework, effort that quietly drifts from the goal, and finished deliverables that answer the wrong question. Purpose questions also tend to arrive mid-project, from stakeholders, at the worst possible time to answer them.",
does="The brief contains the purpose work inside ten structured minutes at the start, when it is cheapest. Five questions produce the essential thinking a WHY-primary generates naturally: who the work serves, what it changes, and why it matters now. Answered once and posted where the work lives, the brief becomes the reference point for every scope decision, status update, and stakeholder conversation that follows.",
device_title="The five questions",
device=[("Who is this for?","Name the actual person or group, not the org chart."),
("What changes if it succeeds?","Describe the after-state in one sentence."),
("Why now?","What makes this the right moment, and what is it competing with?"),
("What does success mean?","How everyone will know, without debate, that it worked."),
("What if we do nothing?","The honest cost of not doing this work.")],
steps=[("Block ten minutes before any planning starts.","If the work has a requester, answer the questions with them in the room. Their answers are the brief."),
("Write plain sentences, not fragments.","One or two sentences per question. If an answer will not come, that is a signal the work is not ready to start."),
("Post it where the work lives.","Top of the project doc, first slide of the deck, pinned in the channel. Refer to it, never regenerate it."),
("Revisit only when scope changes.","The brief is stable by design. If the answers change, the project changed, and everyone should know.")],
wont="This tool will not make purpose work energizing, and it is not meant to. It reduces the cost of tertiary WHY work by containing it: ten structured minutes instead of a recurring drain across the life of the project. For high-stakes or ambiguous work, pair the brief with a review from a WHY-primary colleague, the right partner completes the picture rather than compensating for a gap.",
kit=["Fillable worksheet (print + digital)","Facilitator prompts","Example completed brief"],
pairs=[(22,"North Star One-Pager"),(24,"The So-What Translator"),(29,"The Opening Line Habit")]),

dict(num=22, collection="C", mode="Replace", title="The North Star One-Pager",
lead="The purpose of a project, captured once, usually extracted from the person who holds it, and kept visible for its whole life. <b>The why never has to be regenerated mid-flight.</b>",
drain="Projects demand their purpose repeatedly: in kickoffs, steering meetings, hallway challenges, and every new stakeholder conversation. For WHAT-HOW and HOW-WHAT profiles, producing that articulation fresh each time is a recurring drain, and the version produced under pressure is rarely the best one.",
does="The one-pager does the articulation exactly once, at the start, at full quality, often by borrowing it directly from the sponsor or WHY-primary who already holds it. From then on the answer to every purpose question is a pointer, not a performance. It is the difference between owning a script and improvising nightly.",
device_title="What's on the page",
device=[("The change we're making","The before and after, two sentences."),
("Who it serves","The people whose situation improves, named plainly."),
("What success means","The observable result that ends the debate."),
("What we're not doing","The explicit exclusions. This line prevents more drift than any other."),
("The one-line answer","The sentence you give a stakeholder in an elevator. Memorize this one.")],
steps=[("Extract, don't compose.","Interview the sponsor with the Vision Extraction guide. Their words, your page."),
("Get it signed.","The sponsor confirms it in writing. Now it is authority, not just orientation."),
("Post it everywhere the work lives.","Doc header, deck slide two, channel pin. Visibility is the mechanism."),
("Point instead of re-answering.","When purpose gets questioned mid-project, the page answers. That is its whole job.")],
wont="A borrowed purpose only holds if the source had one; if the sponsor cannot fill the page, you have discovered a project risk far cheaper now than later. And the page is not a substitute for believing the work matters, it is a tool for not having to re-derive why, on demand, from a drained place.",
kit=["North Star template","Sponsor sign-off block","Wall + slide formats"],
pairs=[(25,"Vision Extraction Interview"),(21,"Five-Question Purpose Brief"),(26,"Quarterly Altitude Check")]),

dict(num=23, collection="C", mode="Scaffold", title="The Problem Reframe Deck",
lead="A card deck of prompts that pressure-test whether the right problem is being solved. <b>The reframing question gets asked by the cards</b>, so it no longer depends on an instinct that drains you.",
drain="WHY-primaries reflexively ask whether the problem is the real problem; for WHAT-HOW and HOW-WHAT profiles that question rarely arrives unprompted, and enormous execution skill gets spent on precisely solving the wrong thing. The failure is invisible until the excellent solution lands and nothing improves.",
does="The deck supplies the challenge. Ten minutes with five cards, before serious effort is committed, surfaces most of what a purpose review would catch: inherited framings, symptoms dressed as causes, solutions smuggled into problem statements. You do not need the instinct; you need only to answer the cards honestly.",
device_title="Cards from the deck",
device=["Whose problem is this really, and would they describe it this way?","What would make this problem irrelevant instead of solved?","What is the problem behind the problem?","If the obvious fix were forbidden, what would we do instead?","Are we solving this because it matters, or because we know how?","What would a skeptic say we are actually optimizing for?"],
steps=[("Run the deck before committing effort.","Reframing after execution starts costs ten times more, in work and in morale."),
("Draw five cards, answer in writing.","One or two lines each. Written answers cannot hide behind \"we discussed it.\""),
("Watch for the flinch.","The card you want to skip is usually the one holding a finding."),
("Restate the problem, then proceed.","One sentence, revised or confirmed. Now execute with your full energy, aimed.")],
wont="The deck tests the frame; it cannot supply a vision, and it occasionally concludes the original framing was right, which is a success, not a wasted ten minutes. For genuinely strategic ambiguity, bring the flagged cards to a WHY-primary; you will hand them the exact conversation they are wired for.",
kit=["Reframe card deck (print)","Written-answer sheet","Team facilitation variant"],
pairs=[(27,"Assumption Audit"),(21,"Five-Question Purpose Brief"),(30,"Pre-Mortem Protocol")]),

dict(num=24, collection="C", mode="Scaffold", title="The So-What Translator",
lead="A template that converts detailed output into audience meaning. <b>For every section, one completed sentence: \"which means that...\"</b> The reader gets significance without you having to feel it first.",
drain="WHAT-HOW and HOW-WHAT profiles produce work rich in accurate content and light on stated significance, because deriving what it means to the audience is purpose work, and it drains. The audience, especially executives, reads thoroughness without meaning as noise, and the work gets undervalued.",
does="The translator is a mechanical move that manufactures meaning from content you already have. Each major section of a deliverable gets one forced completion, \"which means that, for this reader...\", and the strongest completion gets promoted to the front. The output reads as strategic; the process was procedural.",
device_title="The translation move",
device=[("List the sections","Every major finding, feature, or component of the deliverable."),
("Force the completion","For each: \"...which means that, for this audience,\" finished honestly in one line."),
("Rank the completions","Which one changes a decision the reader actually faces?"),
("Promote the winner","It becomes the opening line or executive summary. Detail follows as support."),
("Cut the orphans","A section with no honest completion may not belong in this version.")],
steps=[("Name the specific reader first.","\"Which means that\" has no answer without a who. A title and a current worry."),
("Complete every section, no exceptions.","The discipline is the tool. Skipped sections are where meaning was needed most."),
("Lead with meaning, follow with detail.","Your instinct orders it the other way. For mixed audiences, invert it."),
("Keep the appendix.","The full detail survives, one layer down, for the readers wired to want it.")],
wont="The translator produces stated significance, not strategy; it cannot tell you whether the work matters, only say clearly what it means if it does. And for HOW-primary audiences, ease off, they trust detail-first ordering, and over-translated content reads to them as thin.",
kit=["Translator worksheet","Reader profile card","Before/after example"],
pairs=[(28,"Narrative Arc Template"),(29,"The Opening Line Habit"),(40,"Mixed-Audience Deck Structure")]),

dict(num=25, collection="C", mode="Replace", title="The Vision Extraction Interview",
lead="A structured interview that pulls the vision out of the person who holds it, before execution begins. <b>Purpose gets borrowed from a primary source instead of generated from a drained one.</b>",
drain="Executing against a vision you were never really given is a common fate for WHAT-HOW and HOW-WHAT profiles: the sponsor gestures at a direction, you fill the gaps with assumptions, and the gaps surface later as \"that's not what I meant.\" Generating the missing vision yourself is exactly the work that drains you.",
does="The interview replaces generation with extraction. Forty-five minutes of prepared questions, asked of the sponsor or WHY-primary who owns the intent, produces the vision in their words: what done looks like, what made it urgent, what would count as failure. You capture and structure, which is your energy, not theirs to waste.",
device_title="The interview questions",
device=[("What does done look like, a year out?","Push past deliverables to the changed situation."),
("What made this urgent now?","The trigger reveals the real priority ordering."),
("Delivered exactly as specified, what could still make you call it a failure?","This question earns its length. It surfaces the unstated intent."),
("Who else has to believe in this?","The map of people the vision must survive contact with."),
("What are you explicitly not asking for?","Their exclusions, in their words, on the record.")],
steps=[("Book it before planning, not after.","Extraction after execution starts becomes negotiation. Get the vision while it is cheap."),
("Ask, then be quiet.","The pauses are where the real answers live. Resist filling them with options."),
("Read their answers back.","\"Here is what I heard\" in their own words. Correction now is nearly free."),
("Convert straight to the North Star page.","The interview is the raw material; Tool 22 is the artifact it becomes.")],
wont="An interview cannot extract a vision that does not exist, and discovering that vacuum is one of its most valuable outcomes, escalate it, in writing, before building anything. The tool moves the purpose burden to where it belongs; it does not eliminate the need for the purpose to exist.",
kit=["Interview guide","Read-back script","North Star handoff template"],
pairs=[(22,"North Star One-Pager"),(21,"Five-Question Purpose Brief"),(42,"The Handoff Contract")]),

dict(num=26, collection="C", mode="Support", title="The Quarterly Altitude Check",
lead="A scheduled, structured zoom-out: ninety minutes, four questions, once a quarter. <b>Perspective becomes an appointment</b> instead of an instinct you have to summon.",
drain="Heads-down excellence is the gift of WHAT-HOW and HOW-WHAT profiles, and its shadow: the world shifts while the work continues beautifully on rails laid for the old world. Noticing the shift requires unprompted big-picture thinking, which is precisely the thinking that does not arrive on its own.",
does="The check makes the zoom-out structural. Four fixed questions, asked on a calendar rhythm rather than when someone feels like it, catch drift while it is still cheap: goals that moved, assumptions that expired, work that would not be started today. The insight comes from the questions, not from an instinct you would have to drain yourself producing.",
device_title="The four questions",
device=[("Is the work still connected to the goal?","Trace it explicitly. \"It was in January\" is not an answer."),
("What changed in the context?","Market, org, priorities, people. Ten minutes of honest listing."),
("Which assumptions expired?","The plan encoded beliefs. Which are no longer true?"),
("What would we not start today?","The hardest question and the one that pays for the whole ritual.")],
steps=[("Put four dates on the calendar now.","Quarterly, ninety minutes, recurring. Unscheduled perspective loses to scheduled execution every time."),
("Answer in writing, keep the answers.","This quarter's answers against last quarter's is where drift becomes visible."),
("Invite a WHY-primary if you can.","Their energy for the conversation raises its quality and lowers your cost."),
("Leave with at most three changes.","The check is a rudder, not a rebuild. Small corrections, quarterly, compound.")],
wont="A quarterly rhythm catches drift, not sudden ruptures; genuine shocks still need ad hoc response. And the check only works if the fourth question is allowed real answers, a ritual where nothing may ever be stopped is theater, and your wiring will correctly refuse to keep paying for it.",
kit=["Altitude check worksheet","Quarter-over-quarter log","Facilitation guide"],
pairs=[(27,"Assumption Audit"),(22,"North Star One-Pager"),(43,"Team Energy Audit")]),

dict(num=27, collection="C", mode="Scaffold", title="The Assumption Audit",
lead="A checklist that surfaces the unexamined premises baked into a plan, before execution effort is invested in them. <b>The beliefs get listed, tested, and owned on purpose.</b>",
drain="Every plan encodes beliefs: about demand, about people, about what stays constant. Surfacing them is WHY work, questioning the frame rather than the contents, and for tertiary WHY profiles it does not happen unprompted. Untested assumptions fail silently, and flawless execution amplifies them.",
does="The audit is a procedural pass, thirty minutes against a finished plan, that extracts the assumptions the way a checklist extracts details. Each belief gets written down, rated for confidence and consequence, and either accepted out loud or assigned the cheapest available test. Rigor doing the job of instinct.",
device_title="The audit prompts",
device=["What must be true for this plan to work? List everything, obvious included.","Which of these beliefs are inherited, from a predecessor, a template, a habit, rather than tested?","Which single assumption, if wrong, does the most damage?","What evidence would change our mind, and are we positioned to see it?","What is the cheapest test for the riskiest belief?"],
steps=[("Audit the finished plan, fresh.","Assumptions hide best from their authors. Do the pass a day after planning, not during."),
("Write every belief, however obvious.","\"Obviously\" is the costume assumptions wear. The obvious ones fail hardest."),
("Rate on two axes.","Confidence and consequence. High-consequence, low-confidence items are the audit's product."),
("Test or accept, in writing.","Cheapest test for the risky ones; explicit acceptance for the rest. Silent assumptions are the only forbidden kind.")],
wont="The audit finds the beliefs; it does not adjudicate them, judgment and sometimes real research still follow. And it examines the plan's premises, not its purpose, pair it with the Reframe Deck when the deeper question is whether this is the right problem at all.",
kit=["Audit worksheet","Two-axis rating grid","Cheapest-test menu"],
pairs=[(23,"Problem Reframe Deck"),(6,"Edge-Case Question Bank"),(30,"Pre-Mortem Protocol")]),

dict(num=28, collection="C", mode="Scaffold", title="The Narrative Arc Template",
lead="A five-beat structure that converts detail-rich content into a meaning-led story. <b>The narrative is assembled, not inspired</b>, from material you already have.",
drain="Turning content into story is purpose work: it requires deciding what it all means and to whom. WHAT-HOW and HOW-WHAT profiles present the way they work, completely and in order, and audiences wired for meaning check out by slide three, taking the work's reputation with them.",
does="The arc is a fixed five-beat skeleton that any body of content can be poured into. Each beat has a plain question; answering the five questions in order produces a story-shaped deliverable without requiring a storyteller's instinct. The same rigor that built the content now assembles its narrative.",
device_title="The five beats",
device=[("Situation","Where things stand, in terms the audience already accepts. One beat, not five."),
("Stakes","Why standing still costs something. This beat earns the audience's attention."),
("Shift","The insight or change, the one thing this deliverable exists to say."),
("So-what","What it means for the people in the room. Borrow from the Translator."),
("Ask","The specific decision or action requested. Stories without asks are entertainment.")],
steps=[("Write the Shift beat first.","One sentence: the single thing they must take away. Every other beat serves it."),
("Ration the Situation.","Your instinct is to establish everything. The arc allows one beat of context; the rest goes to the appendix."),
("Pour, don't rewrite.","Map existing sections to beats. Most of the work is reordering and cutting, not creating."),
("Read it aloud once.","A story has a sound. If a beat clunks, it is usually Situation overgrowing its slot.")],
wont="The arc structures meaning; it cannot invent significance that is not there, if the Shift beat is empty, the finding is about the work, not the template. And not every artifact needs an arc, reference material should stay reference-shaped. Use it where an audience must be moved.",
kit=["Arc planning sheet","Beat-mapping worksheet","Before/after example deck"],
pairs=[(24,"The So-What Translator"),(40,"Mixed-Audience Deck Structure"),(29,"The Opening Line Habit")]),

dict(num=29, collection="C", mode="Teach", title="The Opening Line Habit",
lead="A micro-practice: every email, deck, and deliverable opens with one sentence of purpose before any content. <b>Small, trainable, and disproportionate in effect.</b>",
drain="Purpose framing drains WHAT-HOW and HOW-WHAT profiles at every scale, including the smallest: the email that starts mid-process, the deck that opens on data, the update that assumes the reader remembers why. Each costs the reader orientation, and collectively they cost the writer a reputation for meaning.",
does="The habit shrinks the purpose burden to a single trained sentence. One line, from a small set of learnable openers, placed before the content in everything you send. It is the minimum effective dose of WHY work: fifteen seconds of drain that saves every reader minutes and reframes how your thinking is perceived.",
device_title="The openers",
device=["\"This matters because...\", the direct form, works almost everywhere.","\"The decision this enables is...\", strongest for executive readers.","\"By the end of this you'll know...\", best for documents and presentations.","\"We're doing this so that...\", best for instructions and requests.","\"Nothing needed from you; this is so that...\", the FYI form, prevents mis-escalation."],
steps=[("Pick two openers and drill them.","Habit needs a small menu. Two forms cover ninety percent of what you send."),
("Write the line last, place it first.","After the content exists, the purpose line takes fifteen seconds. Before, it takes real energy."),
("Apply it to everything for two weeks.","Including trivial messages. The habit forms on volume, not on importance."),
("Watch the replies change.","Fewer clarifying questions, faster responses. The feedback loop is what locks the habit in.")],
wont="One sentence is orientation, not strategy; documents with real stakes still need the Brief or the Arc behind them. And the habit will feel mechanical at first, that is what training a tertiary micro-skill feels like, and mechanical done consistently beats inspired done never.",
kit=["Opener reference card","Two-week habit tracker","Before/after inbox examples"],
pairs=[(24,"The So-What Translator"),(21,"Five-Question Purpose Brief"),(18,"Progress Broadcast Template")]),

dict(num=30, collection="C", mode="Teach", title="The Pre-Mortem Protocol",
lead="A structured session held before launch: it is twelve months from now, and this failed. <b>Working backward from imagined failure gives systematic thinkers a concrete doorway into strategic thinking.</b>",
drain="Asked to \"think big picture,\" WHAT-HOW and HOW-WHAT profiles reach for the register they trust, specifics, and abstract strategic speculation drains them without producing much. The result is that strategic risk conversations happen without the people who best understand how things actually break.",
does="The pre-mortem flips the register. By declaring the failure as fact and asking for its causes, it converts strategy into diagnosis, which is concrete, systematic work these profiles are exceptional at. The protocol produces a ranked map of real risks, generated by the wiring usually left out of the strategy room.",
device_title="The session",
device=[("Declare the failure","\"It is twelve months out. This failed completely.\" Said as fact, not hypothesis."),
("Write in silence","Everyone lists reasons independently, ten minutes. Silence protects the uncomfortable answers."),
("Cluster the causes","Group the reasons; the clusters are the risk map."),
("Rank by likelihood times damage","A simple two-axis pass, exactly the judgment this wiring does well."),
("Counter the top three","One named owner and one concrete counter per top risk, added to the plan.")],
steps=[("Run it after planning, before commitment.","Late enough that there is a real plan to kill; early enough that findings can change it."),
("Enforce the silent writing.","Spoken-first sessions converge on the safe answers. The written round is the protocol."),
("Let specifics stay specific.","\"The integration fails in week three\" is a strategic finding. Do not launder it into abstraction."),
("Close the loop at the real twelve months.","Compare imagined failure to actual history. The calibration compounds.")],
wont="A pre-mortem surfaces failure paths; it does not choose the destination, it stress-tests one already chosen. Vision work still belongs upstream, and to the people energized by it. This is the tool for making sure their vision survives contact with how things actually work.",
kit=["Facilitation script","Silent-round sheets","Risk map + counter template"],
pairs=[(27,"Assumption Audit"),(6,"Edge-Case Question Bank"),(23,"Problem Reframe Deck")]),

# ---------------- COLLECTION D ----------------

dict(num=31, collection="D", mode="Support", title="The Energy Budget Planner",
lead="A weekly calendar audit that tags work by orientation and rebuilds the schedule around your energy. <b>Tertiary work gets placed at peak hours, in limited doses, with recovery adjacent.</b>",
drain="Most calendars are built by request order, not by energy, so tertiary work lands wherever it falls, usually at the tired end of days, where it costs the most and gets done worst. The drain is fixed by wiring; the placement is not.",
does="The planner is a thirty-minute weekly pass: every significant block gets tagged by orientation, marked primary, secondary, or tertiary against your profile, and tallied. Tertiary work then gets moved deliberately to high-energy windows, capped in volume, and followed by primary-orientation recovery. The drain stays; the cost per unit drops sharply.",
device_title="The weekly audit",
device=[("Tag","Every block: is this WHY, WHAT, or HOW work, mostly?"),
("Mark","Against your profile: primary, secondary, or tertiary energy."),
("Tally","Hours per level. The tertiary number is usually a surprise."),
("Place","Move tertiary blocks to your peak windows. Never the end of a depleted day."),
("Recover","Schedule primary-orientation work immediately after every tertiary block.")],
steps=[("Audit last week before planning next.","The tags on real history are honest; the tags on intentions are hopeful."),
("Watch the tertiary trend line.","One heavy week is life. A rising trend is a role drifting away from your wiring."),
("Protect the placement.","A tertiary block moved to peak hours only works if it is defended like a client meeting."),
("Bring chronic overload to the Triage Tree.","The planner optimizes placement. Volume problems need Tool 32.")],
wont="Scheduling cannot convert draining work into energizing work; it lowers the price, not the fact, of the drain. And if the tally shows a role that is majority-tertiary, no planner fixes that, it is evidence for a conversation about the shape of the role itself.",
kit=["Weekly audit sheet","Tagging guide per profile","Trend log"],
pairs=[(32,"Tertiary Triage Decision Tree"),(5,"Timeboxed Detail Sprints"),(34,"Drain Signals Field Guide")]),

dict(num=32, collection="D", mode="Teach", title="The Tertiary Triage Decision Tree",
lead="A repeatable decision path for any draining task: scaffold it, timebox it, trade it, or automate it. <b>White-knuckling stops being the default strategy.</b>",
drain="Without a method, tertiary work gets handled the same way by everyone: endure it, procrastinate it, or silently resent it. All three cost more than the work itself, and none of them are strategies. The missing piece is a decision, made once, about how each recurring drain will be handled.",
does="The tree routes every recurring tertiary task down one of four paths based on two questions: is it structurable, and does it energize someone else? Each path leads to a specific tool in this library. Ten minutes of triage converts a standing drain into a managed one, with a named method attached.",
device_title="The four paths",
device=[("Scaffold it","Recurring and structurable: build the template or checklist once, run it forever. Tools 1-8, 11-19, 21-29."),
("Timebox it","Small, unavoidable, unstructurable: contain it to scheduled peak-energy doses. Tools 5 and 31."),
("Trade it","Draining for you, energizing for a colleague: the framework's favorite move. Tools 10, 20, 33."),
("Automate it","Repeatable and rule-based: hand it to software or AI entirely. Tool 9 and its cousins.")],
steps=[("List your recurring drains.","The Energy Budget tally is the input. Recurring is the keyword; one-offs just get done."),
("Ask the two questions per item.","Structurable? Someone's primary? The answers pick the path."),
("Attach a named tool to each.","Triage without a tool is a diagnosis without a prescription."),
("Re-triage quarterly.","Teams change, tools improve, trades open up. The tree is a habit, not a one-time sort.")],
wont="Triage manages the drain; a fraction of tertiary work always remains that must simply be done, and the honest frame is that it will cost energy and that is acceptable in bounded doses. What is not acceptable is unbounded, unmanaged, undiscussed drain, which is what the tree exists to end.",
kit=["Decision tree card","Recurring-drain inventory","Path-to-tool map"],
pairs=[(31,"Energy Budget Planner"),(33,"Team Trade Board"),(9,"AI Precision Companion")]),

dict(num=33, collection="D", mode="Replace", title="The Team Trade Board",
lead="A team ritual for openly trading work out of tertiaries and into primaries. <b>Under the energy model, a trade is not a favor exchange, it is a net energy gain on both sides.</b>",
drain="On most teams, everyone quietly carries their own tertiary load, because handing off draining work feels like an admission, or an imposition on others. The framework says the opposite: the task draining one person is often the task that energizes another, and the silence is leaving that gain unclaimed.",
does="The board makes the exchange explicit and mutual. Each person posts a recurring drain and something they would gladly take in exchange; profiles make the matches predictable, WHY-WHAT detail work finds HOW-primary takers, HOW-WHY momentum work finds WHAT-primary takers. Matched trades get contracted in writing and reviewed monthly.",
device_title="How a trade works",
device=[("Post the drain","One recurring task, honestly named, with its real weekly cost."),
("Post the offer","What you would happily absorb in return, from your primary."),
("Match by profile","The team map predicts the pairings. Drains meet primaries."),
("Contract the swap","One page: scope, standards, duration. Ambiguous trades curdle."),
("Review monthly","Balanced? Working? Continue, adjust, or unwind, out loud.")],
steps=[("Launch it with profiles on the table.","The board works because the energy logic is shared. Run it after a team MindPrint&trade; session, not cold."),
("Leaders post first.","A leader trading away a drain licenses everyone else's honesty."),
("Keep trades roughly equivalent.","Not identical, equivalent in load. Lopsided trades become resentments with paperwork."),
("Celebrate the completed swap.","The first successful trade converts skeptics faster than any explanation of the model.")],
wont="Not every drain has a taker, and the board must not become a pressure mechanism, an unmatched post simply routes back to the Triage Tree's other paths. Trades also move energy, not accountability: the original owner still answers for the outcome unless the role itself formally changes.",
kit=["Trade board template","One-page trade contract","Monthly review script"],
pairs=[(37,"Team MindPrint&trade; Map"),(32,"Tertiary Triage Decision Tree"),(43,"Team Energy Audit")]),

dict(num=34, collection="D", mode="Teach", title="The Drain Signals Field Guide",
lead="A guide to recognizing depletion early, in yourself and in teammates. <b>The signals arrive well before the burnout conversation</b>, for those who know what to look for.",
drain="Tertiary drain rarely announces itself; it accumulates. By the time it is visible as disengagement or exhaustion, it has been running for months. The early signals are specific and observable, but only if someone is watching for them with a framework in hand.",
does="The guide catalogs the early signatures of sustained tertiary load: the behavioral tells, the quality patterns, the meeting-specific irritability that maps to orientation rather than mood. Read against a team's profiles, the signals become diagnostic, pointing not just at who is drained but at which work is draining them.",
device_title="The early signals",
device=[("Avoidance with a pattern","One category of task perpetually re-prioritized, while everything else moves."),
("Quality inversion","Errors appearing specifically in detail, follow-through, or framing, whichever matches the tertiary."),
("Meeting-type irritability","Fine in some rooms, visibly depleted in others. The room type names the drain."),
("Disproportionate recovery","A small task in the tertiary costing an afternoon of flatness afterward."),
("Language shifts","\"I just need to push through\" and its cousins, said about the same work, repeatedly.")],
steps=[("Learn your own signature first.","Which two signals show up for you? Self-recognition is the entry point."),
("Read teammates against their profiles.","The same behavior means different things in different wirings. The profile is the key."),
("Name it as structure, never as character.","\"That work is expensive for your wiring\" opens a conversation. \"You seem checked out\" closes one."),
("Route findings to the fix.","Signals lead to the Energy Budget, the Triage Tree, or the Trade Board, not to a pep talk.")],
wont="The guide reads energy patterns; it is not a wellbeing assessment, and sustained distress has causes far beyond work design that deserve real support, not a framework. Use the guide for what it sees, structural mismatch between wiring and load, and stay humble about everything else.",
kit=["Signal reference sheet per profile","Self-observation log","Manager conversation guide"],
pairs=[(31,"Energy Budget Planner"),(43,"Team Energy Audit"),(33,"Team Trade Board")]),

# ---------------- COLLECTION E ----------------

dict(num=35, collection="E", mode="Scaffold", title="The Orientation-Balanced Agenda",
lead="A meeting agenda template with a segment that serves each orientation, in a deliberate order. <b>No orientation spends the whole meeting drained</b>, and each contributes from its energy.",
drain="Most meetings are built in one orientation's image: all-vision meetings that never land, all-status meetings that never mean anything, all-detail meetings that never move. Whoever is wired differently spends the hour depleted, and the meeting loses exactly the contribution it needed from them.",
does="The template sequences the meeting through all three energies on purpose: a purpose frame that orients, a decision-and-action core that moves, a scheduled precision pass that catches what speed missed, and a close that converts it all into commitments. Everyone works from their primary at least once per meeting.",
device_title="The agenda blocks",
device=[("Purpose frame","Five minutes: why this meeting, what decision it serves. The WHY energy opens."),
("Decisions and actions","The core: options, calls, owners. The WHAT energy drives."),
("Precision pass","Ten scheduled minutes: edge cases, dependencies, what breaks. The HOW energy, invited rather than interrupting."),
("The close","Closing Card: one action, one owner, one date, written in the room.")],
steps=[("Publish the blocks in the invite.","When HOW-primaries know their pass is coming, they stop fighting for airtime early."),
("Hold the frame to five minutes.","Purpose orients; it does not need to philosophize. The timer protects the WHATs."),
("Protect the precision pass fiercely.","It is the first block cut when time runs short, and cutting it is how meetings ship broken decisions."),
("Rotate who opens each block.","Ideally by primary orientation. The Keeper Cards make this a system.")],
wont="A balanced agenda cannot rescue a meeting with no purpose, and not every gathering needs all four blocks, a pure working session can skip the frame. The template is for decision meetings, where all three energies genuinely have work to do.",
kit=["Agenda template (30/60/90 min versions)","Invite language","Block timing card"],
pairs=[(41,"Meeting Keeper Cards"),(12,"The Closing Card"),(36,"Three-Question Kickoff")]),

dict(num=36, collection="E", mode="Scaffold", title="The Three-Question Kickoff",
lead="A project kickoff protocol requiring the why, the what, and the how each be answered before work starts. <b>Ten minutes that prevents the three classic mid-project stalls.</b>",
drain="Projects stall in three predictable ways: purpose challenges that surface at the steering meeting, momentum that never establishes, and execution surprises that were visible from day one to anyone who looked. Each stall traces to one orientation's question going unanswered at kickoff.",
does="The protocol asks all three questions, out loud, with the team present, and does not close the kickoff until each has a written answer. It takes minutes when the answers exist and surfaces a project risk immediately when they do not, which is the cheapest possible time to find out.",
device_title="The three questions",
device=[("Why does this matter, and to whom?","The purpose in two sentences, from the sponsor's mouth if possible."),
("What does progress look like in two weeks?","The first visible milestone and who is watching for it."),
("How will the work actually get done?","The mechanism: people, sequence, dependencies, the first three tasks.")],
steps=[("Ask them in order, why first.","Purpose frames progress; progress frames mechanism. The order is the protocol."),
("Write the answers on one page.","The kickoff page becomes the project's header: brief, milestone, mechanism."),
("Treat a missing answer as a finding.","A kickoff that cannot answer one question has located the project's first risk, before it cost anything."),
("Assign each answer a keeper.","One person per question owns noticing when its answer stops being true.")],
wont="Three questions are a floor, not a plan; real projects still need the full planning their size demands. The protocol guarantees only that no project starts with one of its three load-bearing questions silently unanswered, which is more protection than most kickoffs provide.",
kit=["Kickoff one-page template","Facilitator script","Keeper assignment card"],
pairs=[(35,"Orientation-Balanced Agenda"),(21,"Five-Question Purpose Brief"),(15,"Milestone Backplanning")]),

dict(num=37, collection="E", mode="Support", title="The Team MindPrint&trade; Map",
lead="A one-page visual of the team's profile composition: where energy concentrates, which orientation is uncovered, and whose role is misloaded. <b>The team's wiring, on one page, in the room.</b>",
drain="Teams discuss workload, skills, and personalities, and almost never discuss energy composition, because there has been no shared artifact to discuss it with. The costs stay invisible: an orientation nobody covers, a member whose role sits squarely on their tertiary, a hiring plan about to duplicate the majority wiring.",
does="The map plots every member's profile on a single page: primary and secondary coverage across WHY, WHAT, and HOW, tertiary exposure per person against their actual role, and the gaps. It converts a set of individual assessments into a team-level diagnostic that meetings, staffing, and hiring can point at.",
device_title="What the map shows",
device=[("Coverage","How much primary energy the team holds in each orientation."),
("The gap","The orientation with little or no primary coverage, and what predictably goes missing because of it."),
("Misload","Each member's role demands versus their profile: who is structurally working from their tertiary."),
("The hiring arrow","What the next hire's profile should add, before the resume pile makes the decision instead.")],
steps=[("Build it from real assessments.","The map is only as honest as its inputs. Everyone takes the MindPrint&trade; assessment first."),
("Reveal it together, facilitated.","The map lands as liberation or as labeling depending entirely on how it is introduced. Facilitate the first viewing."),
("Mark the gap in every planning session.","\"Nobody in this room is wired to hold the detail\" changes how the plan gets reviewed."),
("Refresh on every team change.","One arrival or departure can move the whole energy balance. The map is living, not laminated."),],
wont="The map shows energy composition, not competence, a gap means an orientation costs the team energy to cover, not that the team cannot cover it. Never use it to gate assignments or evaluate performance; the moment it becomes a sorting tool, people stop answering the assessment honestly, and the map dies.",
kit=["Map template (wall + slide)","First-reveal facilitation guide","Hiring-lens worksheet"],
pairs=[(38,"The Friction Forecast"),(33,"Team Trade Board"),(43,"Team Energy Audit")]),

dict(num=38, collection="E", mode="Teach", title="The Friction Forecast",
lead="A guide to the predictable friction between orientations, readable from the team map. <b>What looks like a personality clash is usually orientation friction</b>, and friction you can forecast, you can design around.",
drain="Cross-orientation friction gets misdiagnosed as interpersonal conflict, and the misdiagnosis is expensive: mediation where design was needed, \"communication workshops\" for what is actually a handoff structure problem, and two capable people each privately concluding the other is difficult.",
does="The forecast catalogs the recurring friction signatures between orientations, where each one predictably appears in a workflow, and the design move that dissolves it. Read alongside the team map, it converts \"those two don't get along\" into \"that handoff is missing a contract,\" which is a solvable problem.",
device_title="The classic frictions",
device=[("The vision handoff stall","WHY energy hands WHAT-shaped goals to HOW wiring with the mechanism missing. Fix: the Handoff Contract."),
("Pace versus depth","WHAT energy reads HOW thoroughness as resistance; HOW reads the pace as recklessness. Fix: agreed thresholds, Tool 11."),
("The reopened decision","WHY energy revisits what WHAT considered closed. Fix: the Decision Deadline log, pointed to, not argued."),
("Precision as obstruction","The edge-case question lands as negativity at the moment of momentum. Fix: the scheduled precision pass, Tool 35.")],
steps=[("Map your team's live frictions to the catalog.","Most \"difficult pairs\" match a signature within minutes of looking."),
("Rename them out loud.","\"This is the pace-depth friction, not a you-two problem\" changes the temperature of the room immediately."),
("Install the design fix.","Every signature has one. Structure resolves what conversation alone keeps re-fighting."),
("Teach the catalog to the team.","A team that can name its frictions in orientation language stops taking them personally.")],
wont="Not all conflict is orientation friction; genuine interpersonal and performance issues exist, and dressing them in framework language delays dealing with them. The forecast covers the large fraction that is structural, and an honest facilitator names which fraction they are looking at.",
kit=["Friction signature catalog","Team mapping worksheet","Design-fix quick reference"],
pairs=[(37,"Team MindPrint&trade; Map"),(42,"The Handoff Contract"),(35,"Orientation-Balanced Agenda")]),

dict(num=39, collection="E", mode="Scaffold", title="Decision Rights by Orientation",
lead="A template that assigns the stages of a decision to the people energized by each stage. <b>Decision load gets matched to cognitive wiring</b>, the way task load already should be.",
drain="Teams assign decisions by seniority and availability, never by energy, so framing gets done by people drained by ambiguity, commitment gets held by people drained by closure, and the decision limps through every stage owned by someone paying full price to carry it.",
does="The template splits any significant decision into four stages and assigns each to primary energy: framing to WHY wiring, option development to WHY and HOW together, the commitment call to WHAT wiring, and execution detail to HOW. Authority stays wherever the org chart puts it; the cognitive work moves to where it is cheapest and best.",
device_title="The four stages",
device=[("Framing","What are we actually deciding, and what does it serve? WHY energy leads."),
("Options","The real alternatives, developed with their mechanics and consequences. WHY and HOW energy together."),
("Commitment","The call, made cleanly and on schedule. WHAT energy leads; this stage must not be held by wiring that resists closure."),
("Execution detail","The decision translated into who-does-what-when. HOW energy leads.")],
steps=[("Use it for decisions that recur or matter.","One-off small calls need no architecture. Quarterly planning, hiring, and roadmap calls do."),
("Assign stages from the team map.","The map shows where each energy lives. Stages follow primaries."),
("Keep authority explicit and separate.","The stage lead runs the cognitive work; the accountable owner still signs. Confusing the two kills the template."),
("Watch the commitment stage.","It is the stage most often held by the wrong wiring, and the reason decisions age. Give it to WHAT energy on purpose.")],
wont="This distributes cognitive load, not accountability, and it is not a consensus mechanism; the accountable owner can overrule any stage. It also needs a minimum of profile diversity to work: a team of one wiring will still find the template useful mostly as a map of which stages it should expect to find expensive.",
kit=["Stage assignment template","Worked example (hiring decision)","Authority-vs-stage explainer"],
pairs=[(37,"Team MindPrint&trade; Map"),(13,"Decision Deadline Ritual"),(36,"Three-Question Kickoff")]),

dict(num=40, collection="E", mode="Scaffold", title="The Mixed-Audience Deck Structure",
lead="A presentation architecture for rooms that contain all three orientations. <b>Each wiring hears what it needs to say yes</b>, in the order that keeps everyone in the room.",
drain="Presenters build decks in their own orientation's image, and mixed rooms punish it: the vision deck loses the HOW-primaries by slide four, the detail deck loses the WHATs by slide two, and the objections that surface afterward are really unanswered orientation questions wearing content costumes.",
does="The structure sequences one deck through all three energies: a purpose-led open that earns the WHYs, an action-and-milestone middle that carries the WHATs, an explicit ask, and a genuine precision appendix that tells the HOWs their questions have real answers waiting. Every wiring gets its yes-condition addressed on purpose.",
device_title="The structure",
device=[("The open, two slides","Why this matters and what it changes. The WHY energy in the room decides here whether to lean in."),
("The middle","What happens, in what sequence, with which milestones and owners. The WHAT spine of the deck."),
("The ask, one slide","The specific decision requested, stated plainly. Never leave it implied."),
("The appendix, as deep as needed","The mechanics, data, and edge cases, complete and findable. Its existence, mentioned early, is what lets HOW-primaries say yes without them.")],
steps=[("Announce the appendix on slide two.","\"Full mechanics are in the appendix and I'll go as deep as you want\" visibly relaxes the precision wiring in the room."),
("Keep the open to two slides.","Purpose earns attention; it cannot hold it. The WHATs are already waiting."),
("Read the room's map if you have it.","A HOW-heavy room inverts the ratio: thinner open, appendix promoted. The structure flexes on composition."),
("Rehearse the ask sentence.","Decks with soft asks produce meetings with soft outcomes. One sentence, memorized.")],
wont="Structure cannot rescue an empty case; the deck still needs a real purpose, a real plan, and real numbers, the architecture just guarantees each reaches the wiring that needs it. And for single-orientation audiences, skip the balance and build to the room, that is what the ratios are for.",
kit=["Deck skeleton (slides template)","Room-composition ratio guide","Ask-slide patterns"],
pairs=[(28,"Narrative Arc Template"),(24,"The So-What Translator"),(37,"Team MindPrint&trade; Map")]),

dict(num=41, collection="E", mode="Support", title="Meeting Keeper Cards",
lead="Three rotating meeting roles, purpose keeper, progress keeper, precision keeper, each with a card of licensed interventions. <b>Every orientation's question gets asked, even when its wiring isn't in the room.</b>",
drain="A meeting's blind spot is its composition: rooms without WHY energy drift from the goal without noticing, rooms without WHAT energy end ownerless, rooms without HOW energy ship unexamined decisions. The missing question is not asked, because asking it is nobody's job and everybody's drain.",
does="The cards make it a job. Three roles rotate each meeting, and each card licenses specific interventions, sentences the keeper is expected to say when the trigger appears. The license matters: an intervention that is a role reads as service, where the same sentence freelanced reads as obstruction.",
device_title="The three roles",
device=[("Purpose keeper","Licensed to say: \"We've drifted from the goal\", \"Which decision does this serve?\", \"Why are we doing this part?\""),
("Progress keeper","Licensed to say: \"We're leaving without an owner\", \"Can we decide this today?\", \"What's the next physical step?\""),
("Precision keeper","Licensed to say: \"We haven't tested the edge cases\", \"What breaks first?\", \"Who maintains this after?\"")],
steps=[("Assign roles at the top of the meeting.","Thirty seconds. Ideally against wiring, primaries keep what energizes them, but any assignment beats none."),
("Put the cards on the table.","Physically. The visible card is what converts a challenge into a role being performed."),
("Thank interventions by name.","\"Good precision call\" trains the room that the questions are the system working."),
("Rotate deliberately.","Occasionally assign against wiring in low-stakes meetings; performing another orientation's question builds real empathy for it.")],
wont="Keeper cards guarantee the questions get asked, not that they get answered well, a precision question still deserves precision thinking, and a room with zero HOW wiring should route the flagged items to one after the meeting. The cards are coverage, not replacement.",
kit=["Three printed role cards","Assignment rotation sheet","Facilitator quick-start"],
pairs=[(35,"Orientation-Balanced Agenda"),(12,"The Closing Card"),(38,"The Friction Forecast")]),

dict(num=42, collection="E", mode="Scaffold", title="The Handoff Contract",
lead="A short template completed at any cross-orientation handoff: <b>what the receiver needs that the sender wouldn't naturally include</b>, made explicit in both directions.",
drain="Handoffs fail in the gap between wirings: WHY energy hands over inspiration and calls it a plan; HOW energy hands over completeness and calls it clarity; WHAT energy hands over urgency and calls it a brief. Each sender includes what their own wiring would need, and the receiver needed something else.",
does="The contract is four questions, answered together in ten minutes at the moment of handoff. It forces the translation each wiring skips: the sender articulates what done means and what they are actually asking for, and the receiver names what their wiring needs to run with it. The gap gets closed while it is still free.",
device_title="The contract",
device=[("What I'm handing you","The work, its state, and its purpose, three sentences from the sender."),
("What you need that I wouldn't think to include","The receiver's line, answered from their wiring: the mechanism, the deadline, the why."),
("What done means","Checkable criteria, agreed now, not discovered at delivery."),
("When we check back","One midpoint touch, dated, before done is due.")],
steps=[("Fill it in together, live.","The contract's value is the conversation it forces. Async templates get filled politely and wrongly."),
("Let the receiver write line two.","The sender cannot know what they habitually omit. That is the entire point of the line."),
("Keep it to one page, always.","A handoff needing more than a page is a project needing a kickoff, use Tool 36."),
("Use it on every cross-orientation handoff for a month.","After a month the questions become reflex and the paper becomes optional. The paper trained the habit.")],
wont="A contract cannot fix a handoff of bad work, and it adds ten minutes that trivial handoffs do not need, use it where the orientations differ and the stakes are real. Its deeper effect arrives with repetition: senders start pre-answering line two, which is what cross-wiring fluency actually looks like.",
kit=["One-page contract pad","Wiring-gap examples per pairing","Habit-month tracker"],
pairs=[(38,"The Friction Forecast"),(25,"Vision Extraction Interview"),(7,"Definition-of-Done Cards")]),

dict(num=43, collection="E", mode="Support", title="The Team Energy Audit",
lead="A quarterly team ritual mapping who is spending sustained time in their tertiary, and why. <b>Structural drain becomes a team agenda item</b> instead of a private endurance test.",
drain="Individual drain has individual fixes, but its causes are usually structural: roles shaped by history rather than wiring, work distributed by availability, a gap orientation silently taxed onto whoever complains least. Left unexamined, the structure keeps refilling whatever energy the individual tools free up.",
does="The audit is a facilitated ninety minutes each quarter. Every member maps their real time across the three orientations against their profile, sustained tertiary load gets flagged without judgment, causes get named as structure, and the findings feed directly into the Trade Board and, where needed, into role design itself.",
device_title="The audit",
device=[("Map","Each person: rough percentage of the quarter spent in WHY, WHAT, and HOW work."),
("Flag","Tertiary share above roughly a quarter of the time, sustained across the period, gets marked."),
("Trace","Every flag gets a structural cause: role shape, coverage gap, inherited task, habit."),
("Route","Causes go to fixes: trades to the Board, placement to the Planner, role-shape findings to the manager, explicitly.")],
steps=[("Run it against the team map.","Profiles on the table first. The audit reads load against wiring; it needs both."),
("Normalize the flag.","Everyone carries some tertiary load; the audit hunts sustained and structural, not occasional and normal."),
("Name the gap tax out loud.","When a team lacks an orientation, someone is paying to cover it. Quarter after quarter, it is usually the same someone."),
("Track the trend, not the snapshot.","One quarter is weather. Three quarters of one person's rising tertiary share is a role redesign waiting to be scheduled.")],
wont="The audit surfaces structural drain; fixing it sometimes exceeds the team's authority, and honest facilitation says so rather than letting the ritual imply powers it lacks. Findings that need role redesign or headcount go upward, in writing, with the map attached, which is precisely how the case gets made.",
kit=["Audit worksheet","Facilitation script (90 min)","Escalation memo template"],
pairs=[(37,"Team MindPrint&trade; Map"),(33,"Team Trade Board"),(31,"Energy Budget Planner")]),
]
