# Collections A (tertiary HOW support) and B (tertiary WHAT support)

TOOLS_AB = [

dict(num=1, collection="A", mode="Scaffold", title="Vision-to-Task Decomposition",
lead="A structured worksheet that walks a goal down four levels, from destination to next physical action. <b>Decomposition runs on structure instead of instinct</b>, so nothing depends on a level of detail thinking that drains you.",
drain="Turning a direction into a complete task list is draining work when your energy lives in purpose and momentum. The instinct is to hold the plan at the milestone level and trust the details to sort themselves out, which is exactly where handoffs stall, effort gets underestimated, and things fall through.",
does="The template carries the decomposition. Four levels, each with its own prompts, walk you from the outcome to the next physical actions with named owners. Worked top to bottom, it produces the task-level picture a HOW-primary builds naturally, in one structured sitting instead of a recurring struggle.",
device_title="The four levels",
device=[("Goal","The outcome in one sentence, taken from your purpose or vision work."),
("Milestones","Three to five checkpoints that would prove the work is on track."),
("Workstreams","The threads of work that have to run under each milestone."),
("Tasks","The next physical actions in each workstream, each with one owner.")],
steps=[("Start from the goal in writing.","One sentence at the top of the sheet. Everything below has to trace back to it."),
("Work one level at a time.","Never jump from goal to tasks. Each level only has to answer for the level above it."),
("Run the completeness prompts.","The prompt card catches the categories this thinking tends to skip: reviews, approvals, coordination, cleanup."),
("Transfer tasks the same day.","Move the bottom level into your tracking tool immediately, before the detail goes cold.")],
wont="This will not make detail planning energizing, and repeated passes will still cost you. It contains the work to one structured session. For complex or high-stakes work, have a HOW-primary review the finished breakdown, the right partner completes the picture rather than compensating for a gap.",
kit=["Decomposition worksheet","Completeness prompt card","Example breakdown"],
pairs=[(2,"Pre-Flight Checklist Library"),(8,"Effort Reality-Check"),(10,"HOW-Partner Review Protocol")]),

dict(num=2, collection="A", mode="Replace", title="The Pre-Flight Checklist Library",
lead="Reusable completeness checklists for the deliverables you produce again and again. <b>Completeness stops depending on memory</b>, the checklist holds the details so you don't have to.",
drain="Remembering every detail before something ships is exactly the work that drains a tertiary HOW. The cost shows up as the missed attachment, the stakeholder nobody told, the step that was obvious in hindsight. Each miss is small; the pattern erodes trust in otherwise strong work.",
does="A pre-flight checklist replaces the remembering. Built once per deliverable type, from launches to proposals to offsites, it captures every detail that has ever mattered, and every new miss gets added so the same mistake cannot happen twice. Running the list takes minutes and requires no detail instinct at all.",
device_title="The starter library",
device=["Launch pre-flight","Proposal and pitch pre-flight","Event and offsite pre-flight","Client deliverable pre-flight","New hire onboarding pre-flight","Blank checklist builder, for anything you ship repeatedly"],
steps=[("Pick your three most repeated deliverables.","Start where the volume is. One checklist per deliverable type."),
("Build from the last three instances.","List what almost got missed each time. That history is the checklist."),
("Run it before every send.","The list is only a replacement if it runs every time, not just when things feel shaky."),
("Add every new miss within a day.","The library compounds. A miss that gets captured is a miss retired permanently.")],
wont="A checklist cannot judge quality or catch a problem it has never seen. It retires known misses; it does not generate precision thinking. For novel, high-stakes work, pair it with a HOW-primary review before the deadline, not after.",
kit=["Five starter checklists","Blank checklist builder","Miss-capture log"],
pairs=[(3,"The Last 10% Protocol"),(7,"Definition-of-Done Cards"),(9,"AI Precision Companion")]),

dict(num=3, collection="A", mode="Scaffold", title="The Last 10% Protocol",
lead="A defined closing ritual for any deliverable. <b>The hardest part of finishing becomes a checklist, not a judgment call</b>, run in one pass before anything ships.",
drain="For WHY-WHAT and WHAT-WHY profiles the finish line moves: the interesting problem is solved, energy has already shifted to the next thing, and the closing details, quality passes, edge cases, handoffs, feel like the work is over. That last ten percent is where reputations quietly leak.",
does="The protocol turns closing into a fixed sequence of five passes, run in order, every time. Nothing relies on noticing what needs finishing; the ritual asks the same questions of every deliverable. It takes thirty focused minutes and converts almost-done work into actually-done work.",
device_title="The five closing passes",
device=[("Quality pass","Read or run the whole thing once, end to end, as the recipient will."),
("Edge cases","What breaks at the boundaries, the first use, the odd input, the handoff?"),
("Handoffs","Who receives this, and do they have everything they need to act on it?"),
("Loose ends","Open comments, placeholder text, unsent notifications, stale links."),
("Sign-off","Named person confirms done against the definition of done.")],
steps=[("Schedule the pass as its own block.","Thirty minutes, separate from the making. Closing is a different mode of work."),
("Run the passes in order.","The sequence matters; quality before edge cases, edge cases before handoffs."),
("Use the checklist physically.","Print it or keep it open. The point is to remove judgment from the process."),
("Log anything you skip.","A skipped pass is a decision. Write it down so it is a choice, not a leak.")],
wont="It will not make finishing feel satisfying the way starting does, and it cannot replace deep review on complex technical work. It guarantees the floor: nothing ships without the same five questions being asked of it.",
kit=["Closing pass checklist","Printable desk card","Skip log"],
pairs=[(2,"Pre-Flight Checklist Library"),(7,"Definition-of-Done Cards"),(4,"The Detail Debt Log")]),

dict(num=4, collection="A", mode="Support", title="The Detail Debt Log",
lead="A running capture list for details consciously deferred in the moment, reviewed on a fixed weekly rhythm. <b>Deferring stops turning into dropping.</b>",
drain="In the flow of purpose and progress work, small details surface constantly: a number to verify, a person to loop in, a setting to change. Handling each one in the moment breaks momentum; ignoring them means they vanish. Tertiary HOW profiles lose these details not through carelessness but because nothing catches them.",
does="The log is the catch. Any detail you choose not to handle now goes on the list in one line, with enough context to act on later. A fixed weekly review clears the list in a single batch, at a time you chose, instead of details resurfacing as surprises at the worst moments.",
device_title="What a log entry captures",
device=[("The detail","One line, specific enough that future-you knows exactly what it means."),
("Where it lives","The doc, thread, or system it belongs to."),
("What breaks if dropped","Honest stakes. Some details can genuinely be let go."),
("Clear-by date","When it stops being deferrable.")],
steps=[("Keep the log one gesture away.","A pinned note, a card in your tracker. Friction kills capture."),
("Capture instead of handling.","In the moment, one line on the log. Momentum stays intact."),
("Clear it weekly, in one batch.","Thirty minutes, same time each week. Batch-clearing details costs far less than scattered handling."),
("Prune honestly.","If something has rolled three weeks and nothing broke, cross it off on purpose.")],
wont="The log does not do the details, and the weekly clearing session will still be draining work; schedule it at a high-energy time and keep it short. What it removes is the second, worse cost: details lost entirely and discovered by someone else.",
kit=["Log template (print + digital)","Weekly review ritual card","Prune criteria"],
pairs=[(5,"Timeboxed Detail Sprints"),(3,"The Last 10% Protocol"),(31,"Energy Budget Planner")]),

dict(num=5, collection="A", mode="Support", title="Timeboxed Detail Sprints",
lead="A method for batching detail work into short, scheduled, high-energy blocks. <b>The drain gets contained to windows you chose</b>, instead of leaking across the whole week.",
drain="Detail work resisted is detail work that spreads. Left unscheduled, tertiary HOW tasks get pushed to the end of tired days, done badly, or avoided until they become urgent. The drain is real either way; unmanaged, it also comes with guilt and worse output.",
does="Sprints flip the ownership. Similar detail tasks get batched and assigned to short blocks, twenty-five to forty minutes, placed at your highest-energy point in the day, with a hard stop and recovery time in primary-orientation work immediately after. Same work, dramatically lower cost per unit.",
device_title="The sprint recipe",
device=[("Batch","Group similar detail tasks; context-switching multiplies the drain."),
("Place","Schedule at peak energy, never at the end of a depleted day."),
("Box","Twenty-five to forty minutes with a visible timer and a hard stop."),
("Recover","Follow immediately with work in your primary orientation. Recovery is part of the method.")],
steps=[("Collect detail work into a single list.","The Detail Debt Log feeds this directly."),
("Book two sprints a week, recurring.","Protected calendar blocks at your best hours. Treat them like client meetings."),
("One category per sprint.","Numbers sprint, formatting sprint, follow-up sprint. Batching is the multiplier."),
("Stop at the timer.","Unfinished items roll to the next sprint. The hard stop is what makes the commitment sustainable.")],
wont="Sprints reduce the cost of detail work; they do not turn it into something you will look forward to. If sprint volume keeps growing week over week, that is a structural signal: the role is carrying too much tertiary load, and the Triage Decision Tree is the next stop.",
kit=["Sprint planner sheet","Batching categories card","Calendar block templates"],
pairs=[(4,"The Detail Debt Log"),(32,"Tertiary Triage Decision Tree"),(31,"Energy Budget Planner")]),

dict(num=6, collection="A", mode="Scaffold", title="The Edge-Case Question Bank",
lead="A printed set of boundary-testing questions to run against any plan. <b>You borrow the signature question of the HOW orientation as a tool</b>, without needing the instinct behind it.",
drain="HOW-primaries generate edge cases naturally: what happens when volume doubles, when the key person leaves, when the input is malformed. For WHY-WHAT and WHAT-WHY profiles those questions do not arrive on their own, and plans ship with untested boundaries that fail in production, in front of clients.",
does="The bank supplies the questions. Fifteen minutes running a plan against the list surfaces most of what a precision review would catch at the structural level. You do not have to imagine the failure modes; you only have to answer prepared questions honestly.",
device_title="Questions from the bank",
device=["What happens when the volume doubles? When it halves?","Who owns this after launch, and do they know?","What is the first thing that breaks under time pressure?","What are we assuming stays constant that might not?","What happens at the boundaries, the first day, the last day, the handoff?","If the key person is out for two weeks, what stops?"],
steps=[("Run the bank before commitment.","The questions are cheapest before the plan is locked and public."),
("Answer in writing, one line each.","\"Fine\" is not an answer. If the honest answer is \"don't know,\" that is a finding."),
("Flag the top three exposures.","Not everything needs fixing. Name the three that would hurt most."),
("Assign a counter to each flag.","An owner and an action per exposure, added to the plan before it ships.")],
wont="A question bank is not a substitute for domain expertise; it finds structural gaps, not technical ones. For systems with real complexity, use the bank first, then bring the flagged items to a HOW-primary, you will have a far better conversation.",
kit=["Question bank card deck","Exposure log sheet","Facilitation guide for team use"],
pairs=[(30,"Pre-Mortem Protocol"),(10,"HOW-Partner Review Protocol"),(27,"Assumption Audit")]),

dict(num=7, collection="A", mode="Scaffold", title="Definition-of-Done Cards",
lead="A card completed at the start of any piece of work that specifies, objectively, what finished means. <b>Done becomes a fact, not a feeling.</b>",
drain="Without an external definition, \"done\" for a tertiary HOW profile is a feeling, and the feeling arrives early, usually when the interesting part is over. The gap between felt-done and actually-done is where rework, resentment from receivers, and quality surprises live.",
does="The card externalizes the judgment. Before work starts, it captures the objective criteria, the person who confirms them, and, just as important, what is explicitly not included. Finishing becomes checking a card, which requires no precision instinct, only the discipline to write the card first.",
device_title="Anatomy of a card",
device=[("The deliverable","What is being produced, in one plain sentence."),
("The criteria","Three to five checkable facts that must be true. No adjectives."),
("The confirmer","The named person who says done. Not you."),
("The not-included line","What this work explicitly does not cover, agreed up front.")],
steps=[("Write the card before starting.","Five minutes at kickoff. After work begins, the definition bends toward the feeling."),
("Make every criterion checkable.","\"Reviewed by legal\" is checkable. \"High quality\" is not."),
("Agree it with the receiver.","The card is a contract. Their signature criteria beat your assumptions."),
("Check the card, then stop.","When criteria are met, ship. The card also protects you from polishing past done.")],
wont="A card cannot rescue vague work; if you cannot write checkable criteria, the work itself is not yet defined, which is a finding in its own right. And meeting the card is the floor, not the ceiling; judgment still matters above it.",
kit=["Blank card pads (print)","Example cards for common deliverables","Criteria writing guide"],
pairs=[(3,"The Last 10% Protocol"),(11,"Good-Enough Threshold"),(2,"Pre-Flight Checklist Library")]),

dict(num=8, collection="A", mode="Scaffold", title="The Effort Reality-Check",
lead="A structured correction for the chronic underestimation of execution effort. <b>The estimate gets built from tasks and history</b>, not from optimism.",
drain="Estimation lives in the HOW orientation: it requires seeing all the tasks, including the invisible ones. Tertiary HOW profiles estimate from the shape of the work, which reliably misses reviews, revisions, coordination, and cleanup, and the shortfall lands as missed deadlines and weekend recoveries.",
does="The worksheet forces the estimate through a sequence that surfaces the invisible work. Every task gets listed and sized, the standard hidden categories get added explicitly, and the total gets compared against a real past project before a multiplier is applied. The output is a number you can defend.",
device_title="The correction sequence",
device=[("List every task","Use the decomposition worksheet. Estimates on unlisted work are fiction."),
("Size each one","Small, half-day, full-day. Rough is fine; complete is mandatory."),
("Add the invisible work","Reviews, revisions, approvals, coordination, cleanup. It is never zero."),
("Compare to history","Find one comparable past project. What did it actually take?"),
("Apply the multiplier","Whatever ratio history shows, apply it. The pattern is more honest than the plan.")],
steps=[("Never estimate from the shape.","If the tasks are not listed, the estimate is not real yet."),
("Do the history comparison out loud.","Saying \"the last one took double\" makes the multiplier undeniable."),
("Present the corrected number first.","Anchor on reality; let others argue it down explicitly if they choose to."),
("Log actuals when it ends.","Every completed project sharpens your personal multiplier.")],
wont="This corrects structural underestimation; it cannot price genuinely novel work where no history exists. In those cases the honest output is a range with named unknowns, and the worksheet will at least make the unknowns explicit.",
kit=["Reality-check worksheet","Invisible work checklist","Actuals log"],
pairs=[(1,"Vision-to-Task Decomposition"),(15,"Milestone Backplanning"),(10,"HOW-Partner Review Protocol")]),

dict(num=9, collection="A", mode="Replace", title="The AI Precision Companion",
lead="A curated prompt pack for delegating precision work to AI: decomposition, checklists, gap reviews, edge cases. <b>The detail thinking gets generated for you, and you stay the judge.</b>",
drain="Producing detail from scratch, task lists, completeness checks, boundary analysis, is the most draining work a tertiary HOW profile does. It is also the category of thinking AI now does cheaply and quickly, which makes producing it by hand an increasingly poor use of your energy.",
does="The pack contains tested prompts for the five precision jobs, each engineered to return output you can review rather than a blank page you must fill. Reviewing detail costs a fraction of generating it; the companion moves you permanently from producer to editor of precision work.",
device_title="The five prompt families",
device=[("Decompose","Paste a goal, receive a task breakdown with owners and sequence to edit."),
("Checklist","Describe a deliverable, receive a completeness checklist to prune."),
("Gap review","Paste a draft or plan, receive what is missing, ranked by consequence."),
("Edge cases","Paste a plan, receive the boundary conditions and failure modes to consider."),
("Definition of done","Describe the work, receive checkable criteria to agree with your receiver.")],
steps=[("Use the prompts verbatim first.","They are engineered; personalize only after you know the baseline output."),
("Always edit, never forward raw.","AI output is a strong first pass. Your judgment on what matters is the value-add."),
("Feed context generously.","The more real detail you paste in, the less generic the return."),
("Keep what works.","Save your best edited outputs; they become templates and checklists for Tool 2.")],
wont="AI generates plausible detail; it does not know your organization, and it will state wrong things confidently. It replaces the blank-page cost, not the review. Anything high-stakes still deserves a human HOW-primary pass after your edit.",
kit=["Prompt pack (all five families)","Editing guide","Context template"],
pairs=[(1,"Vision-to-Task Decomposition"),(2,"Pre-Flight Checklist Library"),(6,"Edge-Case Question Bank")]),

dict(num=10, collection="A", mode="Replace", title="The HOW-Partner Review Protocol",
lead="A structured way to request a precision review from a HOW-primary colleague. <b>The right partner completes the work</b>, and the protocol makes asking cheap for you and answering easy for them.",
drain="Tertiary HOW profiles often avoid asking for precision reviews: the request feels like exposing a gap, and unstructured asks (\"can you look this over?\") produce either shallow glances or overwhelming teardowns. So the review that would have caught the problem never happens.",
does="The protocol reframes the exchange as designed collaboration, which is exactly what the framework says it is: a structural partnership need, not a favor. A five-line request template tells the reviewer what the work is, what stage it is at, and where to aim, so their precision energy lands where it matters.",
device_title="The five-line request",
device=[("What this is","One sentence on the deliverable and who it is for."),
("What stage it's at","Draft, near-final, or shipping tomorrow. Calibrates depth."),
("What kind of review","Completeness, edge cases, feasibility, or numbers. Pick one or two."),
("Where to push","The area you are least sure of. Aim their energy."),
("When it's needed","A real deadline, with enough runway to act on findings.")],
steps=[("Identify your reviewers in advance.","Two or three HOW-primaries whose review energizes them. This is a trade, not a burden."),
("Send the template, not the ask.","Five lines. Vague requests get vague reviews."),
("Receive findings as findings.","Precision feedback is about the work. Thank the thoroughness; it cost them nothing and saved you plenty."),
("Reciprocate in your primary.","Offer purpose framing or momentum help back. The trade is what makes it durable.")],
wont="A review protocol cannot fix work sent too late to change. Build the review into the timeline, not after it. And this is a requirement for high-stakes work, not a nice-to-have; the framework is explicit that partnership needs are structural.",
kit=["Request template","Reviewer roster sheet","Reciprocity menu"],
pairs=[(33,"Team Trade Board"),(6,"Edge-Case Question Bank"),(9,"AI Precision Companion")]),

# ---------------- COLLECTION B ----------------

dict(num=11, collection="B", mode="Scaffold", title="The Good-Enough Threshold",
lead="A worksheet that defines the shipping criteria before work begins. <b>Done becomes a pre-commitment</b>, not an in-the-moment fight against the pull of one more improvement.",
drain="For WHY-HOW and HOW-WHY profiles, shipping is the drain: there is always a deeper understanding to reach, a cleaner version to build. The decision to release, made in the moment, loses to the pull of completeness every time, and work stays invisible long past the point of value.",
does="The threshold moves the shipping decision to the start, when perspective is intact. Before work begins you define what must be true to release, what further polish would add and what it would cost, and who accepts the work. When the criteria are met, the decision is already made.",
device_title="The threshold questions",
device=[("What must be true to ship?","Three to five checkable criteria. The floor, agreed up front."),
("What would \"better\" add?","Name the marginal value of another week, honestly."),
("What does \"better\" cost?","The delay, the invisibility, the work not started."),
("Who accepts it?","The named receiver whose yes means shipped."),
("The ship date","A real date. Criteria met plus date arrived equals released.")],
steps=[("Fill it in before starting.","Once you are inside the work, the threshold will drift upward. Set it from outside."),
("Agree it with the receiver.","Their standard for acceptable is usually lower than yours. Let that be data."),
("Post it visibly.","The threshold only holds if it is in view when the pull toward more arrives."),
("Ship at the threshold.","Improvements beyond it go in version two, informed by real feedback.")],
wont="The threshold will not make releasing feel comfortable; the pull toward completeness is your wiring, not a flaw in the tool. What it does is convert an emotional decision into a contractual one. If you override it, do so out loud, as a scope change.",
kit=["Threshold worksheet","Receiver agreement template","Version-two parking lot"],
pairs=[(14,"Version 0.5 Reframe"),(19,"The 48-Hour Draft Rule"),(7,"Definition-of-Done Cards")]),

dict(num=12, collection="B", mode="Scaffold", title="The Closing Card",
lead="An end-of-meeting forcing function: one action, one owner, one date, written before anyone leaves. <b>No conversation ends without becoming movement.</b>",
drain="Rich discussion is energizing for WHY-HOW and HOW-WHY profiles; converting it into commitments is not. Meetings end with deep shared understanding and no owner, and the understanding quietly expires. The pattern reads to others as inaction, whatever the quality of the thinking.",
does="The card is a sixty-second ritual at the end of any working conversation. It demands exactly four lines, which is deliberately minimal: the smallest possible unit of momentum. Filled in and sent while everyone is present, it converts insight into a commitment nobody has to remember.",
device_title="The card",
device=[("One action","The single next physical step. Not a theme, a step."),
("One owner","A name. \"The team\" is not a name."),
("One date","When it will be done, said out loud."),
("One line of context","Why this step, so the card survives out of the room.")],
steps=[("Claim the last two minutes.","Announce it at the start: \"we'll close with the card.\" The ritual needs protected time."),
("Write it in the room.","Not after. The card filled in later is a card filled in never."),
("Send it to everyone present.","One message, four lines. It is the record and the reminder."),
("Open the next meeting with it.","Card review is the first agenda item. Closed loops build the momentum habit.")],
wont="One action per meeting is a floor, not a ceiling; complex sessions need real planning beyond the card. And the card cannot supply follow-through by itself, it makes the commitment visible, which is the condition for follow-through, not the guarantee.",
kit=["Printable card pads","Digital card template","Meeting-open review script"],
pairs=[(18,"Progress Broadcast Template"),(13,"Decision Deadline Ritual"),(41,"Meeting Keeper Cards")]),

dict(num=13, collection="B", mode="Support", title="The Decision Deadline Ritual",
lead="A ritual that timeboxes analysis by setting the decision date in advance. <b>When the date arrives, you decide with the information in hand.</b>",
drain="For profiles whose energy lives in understanding, more analysis always feels justified, and deciding always feels premature. The cost is carried by everyone waiting: decisions age, options expire, and the team reads thoroughness as stalling.",
does="The ritual separates two questions that usually blur together: how good does the information need to be, and when does the decision happen. Both get answered at the start, in writing. Analysis then has a container, and the arrival of the date, not a feeling of readiness, triggers the decision.",
device_title="The ritual",
device=[("Name the decision","One sentence. What exactly is being decided?"),
("Set the date","Proportional to the stakes, not to the interestingness of the analysis."),
("Define good enough","What information would genuinely change the answer? Only that gets gathered."),
("Decide on the date","With whatever is in hand. In writing, with reasons."),
("Log and move","Record the decision and the reasoning, then stop relitigating it.")],
steps=[("Set the date with a witness.","A deadline only you know about is a suggestion. Tell the people waiting."),
("Gather only what changes the answer.","Interesting is not the bar. Decisive is the bar."),
("On the date, write the decision first.","Draft the answer, then check it against the evidence, not the other way around."),
("Review the log quarterly.","You will find the delayed decisions rarely improved with time. That evidence recalibrates you.")],
wont="Some decisions genuinely deserve more time, and the ritual allows extending, once, out loud, with a new date. What it prevents is the silent rolling extension. It also will not make deciding on incomplete information comfortable; it makes it scheduled.",
kit=["Decision sheet","Decision log","Extension protocol card"],
pairs=[(11,"Good-Enough Threshold"),(12,"The Closing Card"),(27,"Assumption Audit")]),

dict(num=14, collection="B", mode="Teach", title="The Version 0.5 Reframe",
lead="A mental model and a vocabulary for shipping imperfect work as data collection. <b>The early release becomes a method of understanding</b>, which is the register this wiring can genuinely accept.",
drain="\"Just ship it\" is advice built for a different wiring. For WHY-HOW and HOW-WHY profiles, releasing incomplete work feels like publishing an error, and no amount of pressure changes that feeling. The drain is not the work; it is the exposure of the unfinished.",
does="The reframe routes shipping through what already energizes you: understanding. A version 0.5 is not a flawed product, it is an instrument for gathering the one kind of information analysis cannot produce, contact with reality. Framed as data collection, early release becomes intellectually defensible, then habitual.",
device_title="The reframes",
device=["A draft is an instrument for collecting data you cannot get any other way.","Feedback on a rough version is cheaper than polish on the wrong version.","Shipped and imperfect beats complete and invisible; invisible work teaches nothing.","The system improves through contact with reality, not through further contemplation of it.","Labeling it v0.5 tells every reader the precision standard it should be held to."],
steps=[("Label the version explicitly.","\"v0.5, for direction not polish\" sets the reader's bar and protects your standard."),
("Ask one specific question with it.","\"Is the structure right?\" turns the release into an experiment with a hypothesis."),
("Log what the feedback taught you.","The log is the proof, in your own evidence, that early release produces understanding."),
("Raise the version, not the delay.","0.5 to 0.8 to done, each on feedback. Iteration is the precision path to quality.")],
wont="The reframe does not apply everywhere; some work genuinely must be right the first time, and your instinct for which is which is trustworthy. It also will not eliminate the discomfort of exposure. It gives the discomfort a purpose your wiring respects.",
kit=["Reframe cards","Version labeling guide","Feedback log template"],
pairs=[(19,"The 48-Hour Draft Rule"),(11,"Good-Enough Threshold"),(18,"Progress Broadcast Template")]),

dict(num=15, collection="B", mode="Scaffold", title="Milestone Backplanning",
lead="A template that converts a deep understanding of the work into dated milestones, built backward from the end. <b>The system view becomes a schedule.</b>",
drain="WHY-HOW and HOW-WHY profiles hold rich maps of what the work involves, but converting the map into a dated sequence of visible checkpoints is momentum work, and it drains. Without it, others see no schedule, and deep progress reads as no progress.",
does="Backplanning starts from the one date that is fixed, the end, and works in reverse, which suits a systems view far better than forward planning does. Each step back asks only: what must be true just before this? The output is a milestone chain others can see and steer by.",
device_title="The backplan",
device=[("Fix the end state","The deliverable and its date, in one line at the right edge of the page."),
("Step backward","What must be true immediately before that? And before that?"),
("Space the milestones","One visible checkpoint every two to four weeks. Visibility is the point."),
("Bring the first one close","The first milestone lands within ten days. Momentum starts now, not later.")],
steps=[("Plan in one sitting, backward only.","Forward planning invites depth-first descent into detail. Backward stays at altitude."),
("Make each milestone demonstrable.","Something you could show, not something you would explain."),
("Publish the chain.","The milestones are for others as much as for you. Post them where the work lives."),
("Re-plan only at milestones.","Between checkpoints, execute. The plan changes at the checkpoints, on purpose.")],
wont="A backplan is deliberately shallow; it is not the task-level plan, and it should not become one. Its job is visible pace. If milestones keep sliding, the finding is usually scope, not discipline, take that to the Good-Enough Threshold.",
kit=["Backplanning template","Milestone spacing guide","Wall-format chain (print)"],
pairs=[(11,"Good-Enough Threshold"),(17,"The Momentum Board"),(8,"Effort Reality-Check")]),

dict(num=16, collection="B", mode="Teach", title="The WIP Limit Practice",
lead="A hard cap on open threads that forces completion before new exploration. <b>Finishing becomes the price of starting</b>, which is the only currency this drain reliably responds to.",
drain="Curiosity opens threads; momentum closes them. For tertiary WHAT profiles the opening is energizing and the closing is not, so open threads accumulate, each one nearly done, none of them shipped, all of them consuming background attention.",
does="The practice is a single rule: no more than three open threads, and a new one cannot open until one closes or is parked, formally and in writing. The rule converts your genuine appetite for the new into the engine that drives completion of the old.",
device_title="The practice",
device=[("Count","List every open thread honestly. The number is usually a surprise."),
("Cap","Three. Not five. The discomfort of three is the mechanism."),
("Close or park to open","A new thread requires a finished one or a formally parked one."),
("Park in writing","Parked means logged with a one-line state, so it can be resumed or retired."),
("Review the lot monthly","Parked items either get a slot, or get retired on purpose.")],
steps=[("Do the first count with a witness.","Accountability at the start; the initial cut from twelve to three is the hard part."),
("Choose the three by receiver value.","Not by interestingness. Whose waiting is most expensive?"),
("Make the parking lot honest.","A park with no written state is just a dropped thread with better branding."),
("Let the cap create the pressure.","When something new excites you, that energy now has one outlet: finish something.")],
wont="A WIP limit cannot make finishing energizing, and the cap will chafe, that is it working. It also needs honest thread-counting; splitting one project into \"sub-threads\" to dodge the cap is a known failure mode. Count like an auditor.",
kit=["Thread inventory sheet","Parking lot template","Monthly review card"],
pairs=[(11,"Good-Enough Threshold"),(17,"The Momentum Board"),(13,"Decision Deadline Ritual")]),

dict(num=17, collection="B", mode="Support", title="The Momentum Board",
lead="A dead-simple visible tracker of movement, three columns, updated weekly. <b>It externalizes the progress sense your wiring doesn't generate internally.</b>",
drain="WHAT-primaries feel progress viscerally; WHY-HOW and HOW-WHY profiles do not, and the absence cuts twice. Real movement goes unfelt and unreported, and stalls go unnoticed until someone else points at them. Both cost credibility that the quality of the work should have earned.",
does="The board is an external progress organ. Three columns, updated in ten minutes each week, on whatever tool the team already uses, a whiteboard, a doc, a channel post. It makes movement visible to you first and to everyone else second, and it makes stalls impossible to miss at week two.",
device_title="The three columns",
device=[("Moved this week","What demonstrably advanced. Demonstrable is the bar, not effortful."),
("Moving now","The active threads, capped by your WIP limit, each with its next step."),
("Blocked","What is stuck, on what, and who owns the unblocking. Named, always.")],
steps=[("Update it at a fixed time.","Friday close or Monday open. The rhythm is the tool; ad hoc boards die."),
("Write for a reader, not a diary.","Entries a colleague could understand cold. That discipline is the reporting."),
("Act on anything two weeks in Blocked.","The board's real alarm. Two weeks stuck means escalate, trade, or retire."),
("Keep it public.","A private board tracks; a public one builds the reputation your work deserves.")],
wont="The board is a method riding on tools you already have; it is deliberately not another piece of software to maintain. It shows movement, it does not create it, pair it with the Closing Card and WIP Limit, which do.",
kit=["Board layout (doc + whiteboard formats)","Weekly update ritual card","Blocked-item escalation guide"],
pairs=[(16,"WIP Limit Practice"),(18,"Progress Broadcast Template"),(12,"The Closing Card")]),

dict(num=18, collection="B", mode="Scaffold", title="The Progress Broadcast",
lead="A fill-in weekly update format, four lines, five minutes. <b>Communicating momentum stops being a writing task and becomes a form.</b>",
drain="The weekly update is a momentum performance, and for tertiary WHAT profiles it drains twice: once to notice what counts as progress, once to write it in the upbeat register the genre expects. So updates get skipped, and silence gets read, wrongly, as stalling.",
does="The broadcast replaces composition with completion. Four fixed lines, Shipped, Moving, Blocked, Next, one sentence each, sourced straight from the Momentum Board. No narrative, no register management, no blank page. The reader gets exactly what they wanted, and it cost you five minutes.",
device_title="The format",
device=[("Shipped","What went out the door this week. Can be \"nothing this week\", said plainly."),
("Moving","The active work and its current state, one line."),
("Blocked","What is stuck and what you need. This line does real work for you."),
("Next","The one thing that moves first next week.")],
steps=[("Send it at the same time weekly.","The reliability is most of the message. Predictable beats polished."),
("Pull from the Momentum Board.","If the board is current, the broadcast is a copy-paste with trimming."),
("Never skip a quiet week.","\"Shipped: nothing, deep in X, on track for the 14th\" is a strong update, not an admission."),
("Use Blocked without apology.","It is the highest-leverage line, a standing, low-cost way to ask for what you need.")],
wont="The broadcast reports momentum; it cannot manufacture it, and dressing up a stalled month in good broadcasts is a misuse that erodes exactly the trust it is meant to build. If Shipped has been empty for three weeks, the tool to reach for is the Threshold, not the thesaurus.",
kit=["Broadcast template (email + chat formats)","Send-time ritual card","Example broadcasts, strong and weak"],
pairs=[(17,"The Momentum Board"),(12,"The Closing Card"),(14,"Version 0.5 Reframe")]),

dict(num=19, collection="B", mode="Teach", title="The 48-Hour Draft Rule",
lead="A protocol: any new deliverable produces a shareable rough draft within forty-eight hours. <b>Refinement comes after contact, not before.</b>",
drain="The natural sequence for a WHY-HOW or HOW-WHY profile is understand fully, then build once, correctly. The cost is the long dark period where nothing is visible and course corrections are impossible, and the deepest work arrives polished but sometimes pointed at the wrong target.",
does="The rule inverts the sequence for the first two days only. Within forty-eight hours of starting, a rough structural draft, ugly on purpose, goes to one named reader with one question attached. Errors of direction get caught at hour forty-eight instead of week four, which protects the deep work that follows.",
device_title="The rule",
device=[("Forty-eight hours","From kickoff to shareable rough draft. Structure, not polish."),
("Labeled v0.5","The label sets the standard it should be judged by. This is armor, use it."),
("One named reader","A person, chosen for judgment, not a distribution list."),
("One question attached","\"Is this the right shape?\" The draft is an experiment; the question is its hypothesis."),
("Then depth","Direction confirmed, the thorough build proceeds with its foundation checked.")],
steps=[("Timebox the draft, two sessions max.","The constraint is what keeps it structural. A week-long \"draft\" defeats the purpose."),
("Draft the skeleton, not the muscle.","Headings, structure, the argument in bullets. Wrong-but-complete beats right-but-partial."),
("Send it before it feels ready.","It will not feel ready at hour forty-eight. That is the design, not a failure of it."),
("Bank the correction.","Each time the reader catches a direction error early, log it. That log is why the rule holds.")],
wont="The rule does not shorten the deep work, and it should not; it protects that work from being aimed wrong. It also is not for everything, small tasks need no draft, and some formal deliverables cannot circulate rough. Use it wherever direction errors are expensive.",
kit=["48-hour protocol card","Draft skeleton templates","Correction log"],
pairs=[(14,"Version 0.5 Reframe"),(11,"Good-Enough Threshold"),(18,"Progress Broadcast Template")]),

dict(num=20, collection="B", mode="Replace", title="The WHAT-Partner Cadence",
lead="A structured pairing with a WHAT-primary who owns pace-setting for a defined piece of work. <b>Momentum becomes someone's energizing job instead of your draining one.</b>",
drain="Every method in this collection reduces the cost of momentum work; none of it makes that work energizing, because for WHY-HOW and HOW-WHY profiles it never will be. On long or high-stakes work, self-managed pace has a failure rate that no worksheet fully fixes.",
does="The cadence protocol formalizes what the framework calls a structural partnership need. A WHAT-primary partner takes explicit ownership of pace: milestones, check-ins, and the standing question \"what ships this week?\" For them the role is energizing. For you it removes the heaviest recurring drain entirely.",
device_title="The cadence agreement",
device=[("Who sets pace","The partner owns dates, check-in rhythm, and the shipping question."),
("The rhythm","A fixed check-in, weekly or twice-weekly, fifteen minutes, no agenda beyond movement."),
("What the partner can call","Slipping milestones, threads over the WIP cap, thresholds drifting upward."),
("What stays yours","Depth, quality, and direction. The partnership divides energy, not authority."),
("The trade","What you carry for them in return, usually depth review or purpose framing.")],
steps=[("Choose a genuine WHAT-primary.","The pairing works because pace-setting energizes them. A reluctant partner recreates the drain, twice."),
("Write the agreement in one page.","Roles, rhythm, call-outs, trade. Ambiguity is where partnerships curdle."),
("Let them push, by contract.","When they press on a date, that is the agreement functioning, not a judgment of you."),
("Review the pairing monthly.","Ten minutes: is the trade balanced, is the rhythm right, does it continue?")],
wont="This is a partnership, not a rescue; it fails if framed as the partner compensating for a deficiency rather than completing a team. The framework is explicit, collaboration needs are requirements. And the trade must be real, a one-way cadence becomes supervision, and nobody signed up for that.",
kit=["One-page cadence agreement","Check-in script","Monthly review card"],
pairs=[(33,"Team Trade Board"),(17,"The Momentum Board"),(10,"HOW-Partner Review Protocol")]),
]
