// MindPrint Profile data for all 6 types.
// Keys match URL slugs: why-what, why-how, what-why, what-how, how-why, how-what

const profiles = {
  'why-what': {
    slug: 'why-what',
    label: 'WHY – WHAT',
    tagline: 'Purpose-Driven, Progress-Oriented',
    signal: 'Before we go further, are we solving the right problem here?',
    whoYouAre: `You arrive at a problem already asking whether it's the right problem. You have an instinctive need to understand purpose before you engage, not as a philosophical exercise, but because you genuinely cannot commit your energy to a direction you don't believe in. Once the purpose clicks, however, you move fast. You translate vision into direction with unusual fluency, articulating not just where the team should go but why the destination matters.`,
    superpower: `At full power, you are a remarkable catalyst for change. You see opportunities others have normalized away, question assumptions the team stopped questioning, and can articulate a path forward that makes people feel both challenged and oriented. You are a natural leader of transformation, not incremental improvement, but genuine reinvention. You give teams permission to think bigger and the directional clarity to actually get there.`,
    energizes: `You are most alive in the space between knowing something must change and knowing what to do about it. You are fueled by possibility. Nothing unlocks your energy quite like a problem that hasn't been properly named yet, one where you can sense the right question hasn't been asked. The moment purpose clicks for you, momentum follows naturally. Transformation work, strategic pivots, and moments where a team needs to think bigger all sit squarely in your zone of highest energy. You don't need perfect information or a guaranteed path, you need to believe the destination is worth going to.`,
    drains: [
      'Process documentation and quality assurance work',
      'Tracking granular task completion across many small steps',
      'Sustained attention to many small interdependent details simultaneously',
      'Being asked to own implementation after vision and direction have been established',
    ],
    blindSpot: `Your blind spot is execution detail. You can see the destination and plot the general path, but the granular mechanics of how the work actually gets done, the dependencies, the process design, the quality checks, are genuinely invisible to you. You don't just deprioritize detail, you often don't see it at all.`,
    friction: `Your most common source of friction is timing. You will pull a team backward, back to purpose, back to the question, at moments when the team believes the decision is made and it's time to execute. To a WHAT or HOW teammate, this feels like obstruction. To you, skipping this step feels reckless. The other significant friction point is your distance from execution detail: you hand off with confidence, but the handoff often contains gaps you genuinely don't see.`,
    needFromTeam: `A strong HOW presence is non-negotiable. You need someone who can receive a vision and roadmap and build the execution architecture underneath it. You also benefit from a WHAT partner who can translate direction into sustained organizational momentum.`,
    howToWorkWithYou: `Lead with purpose when bringing you a problem. Give you room to question the frame before expecting commitment to the plan. Don't interpret your questioning as resistance, it's how you build conviction. Once bought in, you're genuinely all in. Keep you out of granular execution ownership and use you as a periodic strategic lens, bring you back when the team needs to reassess direction or reframe a stuck problem.`,
    valueAreas: [
      'Defining organizational vision and long-range goals',
      'Identifying market opportunities and white space',
      'Setting strategic priorities for a team or business',
      'Rallying stakeholders around a new direction',
      'Leading vision-setting workshops and offsites',
      'Crafting high-level roadmaps and milestone plans',
      'Building and pitching compelling narratives',
      'Making high-stakes decisions with incomplete information',
    ],
    partners: [
      { type: 'HOW-WHAT or HOW-WHY', reason: 'To translate vision into detailed plans, processes, and execution scaffolding' },
      { type: 'WHAT-HOW', reason: 'To move fast on a plan once direction is set and iterate toward the goal' },
    ],
    areasToWatch: [
      "Getting stuck in the 'why' and delaying meaningful action",
      'Losing patience with detailed execution and follow-through',
      'Underestimating the complexity of implementation',
      'Communicating in ways that feel abstract to HOW types',
      "Revisiting decisions already made as new 'why' questions surface",
    ],
    roles: [
      'Chief Executive Officer / Managing Director',
      'Chief Strategy Officer',
      'Founder / Entrepreneur',
      'Head of Innovation',
      'Management Consultant',
      'Executive Coach',
      'Brand Strategist',
      'Product Visionary / VP of Product',
      'General Manager',
      'Political or Nonprofit Leader',
    ],
  },

  'why-how': {
    slug: 'why-how',
    label: 'WHY – HOW',
    tagline: 'Purpose-Driven, Precision-Oriented',
    signal: 'Wait, before we decide — do we actually understand how this system works?',
    whoYouAre: `You are a systems thinker in the deepest sense. You cannot engage comfortably with a problem until you understand both its purpose and its architecture, and you are rarely satisfied when others accept one without the other. You bring an unusual combination of visionary thinking and structural precision, seeing not just where something should go but exactly how its parts must fit together to get there. You are drawn to complexity, energized by the challenge of understanding things fully, and capable of producing work of exceptional quality when given the space to think.`,
    superpower: `At full power, you are the person who solves problems no one else has properly framed. You can hold vision and detail simultaneously, which means you produce plans that are both ambitious and executable, strategies that are both inspiring and rigorous. You are the architect of things that actually work as designed. Organizations bring you their hardest, most tangled problems, because you are one of the few people who will neither oversimplify them nor lose sight of what they are ultimately for.`,
    energizes: `You are most alive at the intersection of a big question and a complex system. You are energized by problems that reward deep understanding — where surface-level thinking produces wrong answers and only genuine comprehension unlocks the right path. Mapping a system no one has fully charted, finding the structural reason something keeps failing, building a framework that makes the invisible visible: these are the moments where you operate at your highest. You don't need speed. You need the freedom to think completely.`,
    drains: [
      'Being pushed to act before the picture feels sufficiently understood',
      "Rapid iteration environments where the ground shifts before work is complete",
      "Being told 'good enough' when better is clearly within reach",
      'Coordination overhead: status updates, check-ins, administrative work',
    ],
    blindSpot: `Your blind spot is momentum. You can see the vision and understand the system deeply, but the pure drive to move, to accept imperfection and iterate, to ship something before it's fully thought through, is genuinely uncomfortable. You can get caught in an elegant loop of refining your understanding without committing to action, and this can frustrate teammates who are ready to move.`,
    friction: `Your most common friction is with WHAT types, who experience your need for thoroughness as a blocker. You will keep pulling a conversation deeper at moments when others believe the thinking is done and it's time to execute. To a WHAT teammate, this feels like perfectionism or obstruction. To you, moving without sufficient understanding feels genuinely reckless. You can also struggle to communicate the depth of your thinking in a way that lands for action-oriented peers.`,
    needFromTeam: `A strong WHAT partner is essential. You need someone who can take your deep thinking and force it into action, who creates the urgency to ship before perfect becomes the enemy of good. Without this partner, your best work risks staying internal indefinitely.`,
    howToWorkWithYou: `Give them genuinely complex problems and real space to think. Don't rush the analysis phase. When you need them to move, frame a clear decision point rather than asking them to accept that the thinking is done. Let them finish their framework before you operationalize it. The depth is the work, not a detour from it.`,
    valueAreas: [
      'Mapping complex systems and identifying interdependencies',
      'Developing frameworks and mental models',
      'Research synthesis and distilling insights into principles',
      'Diagnosing root causes of systemic problems',
      'Building organizational structures aligned to goals',
      'Creating detailed strategic plans from vision to task',
      'Facilitating deep diagnostic conversations with leadership',
      'Designing programs with both purpose and operational rigor',
      'Writing frameworks, white papers, and thought leadership',
      'Articulating the why and the how together in a single plan',
    ],
    partners: [
      { type: 'WHAT-WHY or WHAT-HOW', reason: 'To inject momentum and move deep thinking into action before perfect becomes the enemy of good' },
      { type: 'HOW-WHAT', reason: "To operationalize detailed plans and manage execution against the system they've designed" },
    ],
    areasToWatch: [
      'Moving to action — can over-analyze before starting',
      'Communicating complex thinking to action-oriented WHAT types',
      'Getting bogged down in perfecting the system before testing it',
      'May struggle to ship imperfect work when better is within reach',
      'Can be perceived as theoretical or slow by momentum-driven peers',
      'Undervaluing speed and iteration as a valid strategy',
    ],
    roles: [
      'Chief Architect / Principal Designer',
      'Head of Research and Development',
      'Management Consultant (Systems / Org Design)',
      'Professor or Academic Thought Leader',
      'Policy Strategist',
      'Chief of Staff',
      'Organizational Effectiveness Lead',
      'Innovation or R&D Strategist',
      'Curriculum or Learning Designer',
      'Author / Intellectual Practitioner',
    ],
  },

  'what-why': {
    slug: 'what-why',
    label: 'WHAT – WHY',
    tagline: 'Progress-Driven, Purpose-Oriented',
    signal: 'Okay, we understand the problem — so what are we actually doing next?',
    whoYouAre: `You are built for forward motion with a destination. You move fast and with conviction, and unlike a pure WHAT, you care deeply about where you are headed. You don't just want to make progress — you want to make progress that means something. You are energized by goals that are clear and compelling, and you are a natural force for mobilizing others around them. Your combination of intuition and purpose-orientation makes you a powerful driver in any environment where getting people moving in the right direction is the central challenge.`,
    superpower: `At full power, you are a remarkable motivating force. You translate purpose into momentum in a way few types can, rallying people not just to action but to action they believe in. You make teams feel that what they're doing matters and that progress is possible. You are the person who breaks a complex situation into a clear path forward, who names the goal everyone has been circling, and who creates the energy to actually pursue it. In change-heavy environments, you are essential.`,
    energizes: `You are most alive when a clear goal is in sight and the team needs to move. You are energized by forward motion toward something meaningful. The moment a goal crystallizes, your energy ignites. You thrive in environments where milestones are real, progress is visible, and what you're working toward actually matters. You don't need a fully mapped path. You need a compelling destination and enough room to find your way there through action. Trial and error isn't a failure mode for you — it's how you think.`,
    drains: [
      'Detailed process design and documentation work',
      'Tracking granular tasks rather than meaningful milestones',
      'Long diagnostic conversations that do not produce a next step',
      'Being asked to slow down and fully map before attempting',
    ],
    blindSpot: `Your blind spot is execution complexity. You can see the goal and feel the path intuitively, but the detailed mechanics of how the work gets done, the process scaffolding, the dependencies, the downstream effects, are often invisible to you. You move confidently on intuition, which serves you well until the terrain is more complex than it appeared, and then the gap becomes visible.`,
    friction: `Your most common friction comes from HOW types who need more detail before they can engage, and from WHY-HOW types who want to understand the system before committing to a direction. You interpret this need for depth as delay. They interpret your urgency as recklessness. The other friction point is that you can inadvertently skip important diagnostic steps, arriving at a solution before the problem has been fully understood.`,
    needFromTeam: `A HOW partner to build the execution infrastructure your momentum requires. Someone who can take the goals you've set and build the process scaffolding that makes them sustainable and reliable. You also benefit from a WHY voice who occasionally questions whether the destination is still right.`,
    howToWorkWithYou: `Connect their work to clear, meaningful goals — they will work harder and more effectively when the destination is compelling. Don't burden them with process ownership. Create structured check-in points rather than ongoing oversight. When you need them to slow down, frame it as making the momentum sustainable rather than stopping to review.`,
    valueAreas: [
      'Setting milestones and keeping teams on track toward a goal',
      'Running high-energy standups and progress check-ins',
      'Making fast decisions and course-correcting in real time',
      'Iterating quickly through trial and error toward a solution',
      'Rallying cross-functional teams around shared goals',
      'Driving accountability and tracking key milestones',
      'Navigating ambiguity and finding a path forward quickly',
      'Conducting client-facing discovery and solution pitching',
      'Building and maintaining momentum on long-horizon projects',
      'Creating lightweight project plans and sprint structures',
    ],
    partners: [
      { type: 'WHY-HOW or WHY-WHAT', reason: 'To pressure-test direction and ensure action is grounded in the right purpose' },
      { type: 'HOW-WHAT', reason: 'To manage detailed execution and ensure all moving parts are tracked and handled' },
    ],
    areasToWatch: [
      'Losing patience with detailed process design or documentation',
      'Treating daily tasks as less meaningful than big milestones',
      'May move forward before direction is sufficiently clear',
      'Can overlook downstream execution complexity',
      'Risk of burning out HOW types who bear the execution burden',
      'May skip diagnostic steps and solve the wrong problem',
    ],
    roles: [
      'Sales Leader / VP of Sales',
      'Program or Project Director',
      'Operations Leader',
      'Entrepreneur / Business Builder',
      'Business Development Director',
      'Chief Operating Officer',
      'Team Lead / Scrum Master',
      'Marketing or Growth Lead',
      'Campaign Manager',
      'Change Management Lead',
    ],
  },

  'what-how': {
    slug: 'what-how',
    label: 'WHAT – HOW',
    tagline: 'Progress-Driven, Precision-Oriented',
    signal: 'Can we just agree on a plan and start? We can fix it as we go.',
    whoYouAre: `You are the most complete executor in the framework. You can hold high-level direction and granular detail simultaneously, move with urgency, and course-correct in real time without losing the thread of what you're trying to accomplish. You are energized by the cycle of action and refinement — move, assess, adjust, move again. You trust your gut on direction and your eye on detail, and you rarely need someone else to tell you which is which. What you cannot tolerate is standing still.`,
    superpower: `At full power, you are a remarkable operational leader. You keep complex work moving, hold all the parts in mind simultaneously, and make the continuous small adjustments that keep execution on track. You are the person who ensures that things don't just get started but actually get finished — and finished well. In environments with high complexity and high stakes, you are often the operational backbone that everyone else relies on without fully recognizing.`,
    energizes: `You are most alive when a plan is in motion and the details are yours to manage. You are energized by the full cycle of execution — from initial direction through iteration to completion. Nothing satisfies you quite like a complex initiative that comes together through disciplined action and real-time problem-solving. You don't need the destination to be perfect before you start. You need enough direction to begin, and the freedom to adapt as you move. Metrics, milestones, and visible progress are genuinely motivating to you, not just useful tools.`,
    drains: [
      'Extended strategic or philosophical conversations that do not produce action',
      'Being asked to justify direction when momentum feels self-evident',
      'Vision work disconnected from execution planning',
      'Environments where purpose conversations consistently delay getting started',
    ],
    blindSpot: `Your blind spot is purpose. You trust your gut on direction and can be impatient with conversations that question whether that direction is right. You can come across as closed to strategic reframes, particularly when momentum is already established. The destination feels obvious to you, which makes it genuinely difficult to understand why others keep questioning it.`,
    friction: `Your friction comes primarily from your relationship to purpose conversations. WHY types who question direction feel like obstruction to you, especially once work is moving. You can also overwhelm teammates with the detail and action items generated by your own planning, particularly WHY types who need to understand purpose before engaging with a plan. The gap between how much you've thought through and how much you've shared creates ongoing misalignment.`,
    needFromTeam: `A WHY voice you trust — someone who can periodically pull you back to question the destination without it feeling like obstruction. This is the most important and often most difficult relationship for you to cultivate, because the WHY's instinct to question is precisely what you find most frustrating.`,
    howToWorkWithYou: `Be concrete and action-oriented in how you engage. Bring problems with some initial thinking about next steps. When you need them to reconsider direction, frame it in terms of better outcomes rather than abstract purpose. Give them clear metrics — they genuinely use them and find them energizing rather than constraining.`,
    valueAreas: [
      'Building and managing detailed project plans',
      'Running agile sprints, retrospectives, and planning sessions',
      'Iterating quickly on solutions and testing alternatives',
      'Documenting processes and operationalizing workflows',
      'Balancing short-term execution with longer-term planning',
      'Creating dashboards and metrics to track progress',
      'Breaking big initiatives into actionable work streams',
      'Holding teams accountable to timelines and deliverables',
      'Managing cross-functional dependencies and blockers',
      'Conducting structured post-mortems and lessons learned',
    ],
    partners: [
      { type: 'WHY-WHAT or WHY-HOW', reason: 'To provide periodic direction checks and ensure execution is pointed at the right goal' },
      { type: 'HOW-WHY', reason: 'To add depth of analysis and quality control to work being moved forward' },
    ],
    areasToWatch: [
      'May launch without sufficient strategic clarity from leadership',
      'Can optimize execution of the wrong problem',
      'Risk of over-engineering a process before it is needed',
      'Sometimes struggles to zoom out and evaluate directional shifts',
      'May feel stalled when a clear action plan does not exist',
      'Can have friction with WHY types who resist locking into a plan',
    ],
    roles: [
      'Project Manager / Senior Project Manager',
      'Engineering Manager',
      'Product Manager',
      'Operations Manager',
      'Program Manager',
      'Agile Coach / Delivery Lead',
      'Business Analyst',
      'Chief of Staff',
      'Management Consultant (Delivery-focused)',
      'Startup COO / Generalist Operator',
    ],
  },

  'how-why': {
    slug: 'how-why',
    label: 'HOW – WHY',
    tagline: 'Precision-Driven, Purpose-Oriented',
    signal: 'Before we move on — what happens when X? Has anyone actually tested that assumption?',
    whoYouAre: `You are driven by a profound need to understand how things work — and an equally profound belief that once you understand something deeply enough, you can always make it better. You are not satisfied with the way things are done simply because that's how they've always been done. You see current systems as hypotheses, not facts, and you are always testing. You learn by doing, by taking apart, by running experiments in your mind and in reality. You bring rigor and imagination together in a combination that produces solutions of unusual quality.`,
    superpower: `At full power, you are the person who solves the problems everyone else has given up on. You find the path that wasn't visible before, improve the system that was assumed to be fixed, make the impossible merely difficult. You are inspired by constraints, not defeated by them. You combine deep analytical capability with a genuine belief that things can be better, which means your work doesn't just diagnose problems — it invents solutions. The quality of what you produce when given real space is consistently exceptional.`,
    energizes: `You are most alive when a hard problem has been handed to you and the path isn't obvious. You are energized by genuine complexity — problems that reward depth, that punish surface thinking, where the answer requires understanding the system fully before you can improve it. Finding the flaw in an assumption everyone accepts, redesigning the process that everyone has worked around, solving the problem that has been declared unsolvable: these are the moments where your energy is highest. You don't need speed. You need a hard problem and the autonomy to pursue it properly.`,
    drains: [
      'Project management: creating and maintaining timelines',
      'Rallying people around a plan or managing team momentum',
      'Being pulled from deep work for coordination and status updates',
      'Environments that reward speed and volume over depth and quality',
    ],
    blindSpot: `Your blind spot is deployment. You can tinker and refine past the point of diminishing returns, and you can struggle to transition from deep work to shipping. Your communication can be dense — you have done so much thinking that bringing others up to speed requires significant effort, and you don't always recognize how much context a listener needs. The work can stay internal longer than it should.`,
    friction: `Your friction comes from pace and deliverability. Teams working at speed find your need for depth frustrating, and you find their willingness to move without sufficient understanding genuinely alarming. You can also create friction through communication density — when you share your thinking, the volume and complexity of it can overwhelm colleagues who needed a summary, not a system map.`,
    needFromTeam: `A strong WHAT partner who can take your deep work and build a delivery structure around it — who creates the urgency to ship and manages the organizational momentum you find draining. Without this partner, your best work risks staying internal indefinitely. The WHAT partner is not a compromise, they are what makes your work real.`,
    howToWorkWithYou: `Give them genuinely hard problems and real autonomy over how they approach them. Don't over-structure their process — the tinkering is the work, not a detour from it. Create clear deployment milestones they commit to, but leave the path open. Protect them from organizational overhead — every hour in status meetings is an hour not spent on the work only they can do.`,
    valueAreas: [
      'Deep analytical work: root cause analysis and data modeling',
      'Process auditing and redesign',
      'Synthesizing complex information into clear findings',
      'Benchmarking performance and identifying improvement levers',
      'Building frameworks to evaluate and optimize systems',
      'Writing detailed technical documentation and specifications',
      'Facilitating structured problem-solving sessions',
      'Testing hypotheses and validating approaches rigorously',
      'Spotting inefficiencies and designing elegant solutions',
      'Mentoring teams on methodology and best practices',
    ],
    partners: [
      { type: 'WHAT-WHY or WHAT-HOW', reason: 'To turn insights and analysis into forward momentum and decisive action' },
      { type: 'WHY-WHAT', reason: 'To connect detailed findings to a compelling vision and communicate them to leadership' },
    ],
    areasToWatch: [
      'Moving from analysis to action — can dig past the point of diminishing returns',
      'Communicating findings in a way that drives decision-making',
      'Difficulty prioritizing when everything feels important',
      'Can be resistant to launching before something feels right',
      'May underestimate the importance of momentum and speed',
      'Frustration with teams that move without sufficient grounding',
    ],
    roles: [
      'Data Scientist / Analyst',
      'Process Improvement Lead (Lean / Six Sigma)',
      'Research Scientist',
      'Systems Engineer',
      'Quality Assurance Lead',
      'Organizational Effectiveness Analyst',
      'Technical Architect',
      'Financial Analyst / Controller',
      'Learning and Development Specialist',
      'UX Researcher',
    ],
  },

  'how-what': {
    slug: 'how-what',
    label: 'HOW – WHAT',
    tagline: 'Precision-Driven, Progress-Oriented',
    signal: 'I want to make sure we have the right structure in place before we start moving.',
    whoYouAre: `You are oriented toward making work work. You think in systems — not abstractly, but concretely and operationally. You can see how a process will break before it breaks, how a structure will create the wrong incentives before it's implemented, how the pieces of a complex operation need to fit together for the whole to function. You are energized by complexity that resolves into elegant function. You are not just someone who can manage complexity — you are someone who builds the architecture that makes complexity manageable for everyone else.`,
    superpower: `At full power, you are the operational foundation that allows ambitious organizations to actually function. You build the systems, processes, and structures that turn vision into repeatable reality. You are the person who prevents the team from making the same mistake twice — who encodes learning into process so that the organization gets smarter over time. When you are given ownership of how work gets done, the quality and reliability of output improves in ways that are often invisible precisely because you've prevented the failures before they happened.`,
    energizes: `You are most alive when a complex system needs to be understood and made to work better. You are energized by operational complexity that yields to rigorous thinking. The challenge of understanding how all the parts of a system interact, finding the point where it loses efficiency, and designing the structure that makes it work reliably — this is where your energy is highest. You find genuine satisfaction in watching a well-designed process run smoothly, knowing that the smoothness is the result of careful upstream thinking. Order from complexity is not just a goal for you — it is deeply satisfying.`,
    drains: [
      'Vision work and purpose conversations disconnected from execution',
      'Strategic reframes that disrupt functioning systems',
      'Being asked to justify the meaning of work rather than improve its execution',
      'Open-ended creative sessions without clear operational outputs',
    ],
    blindSpot: `Your blind spot is purpose. You invest deeply in building systems that work, and conversations that question whether those systems are pointed at the right goal can feel threatening rather than generative. You can resist strategic reframes that would require dismantling something you've built — not out of ego, but because you genuinely don't experience the why of the work as the relevant question. The system works. That feels like enough.`,
    friction: `Your friction is with WHY types who question the direction of systems you've built, and with WHAT types who want to move before the infrastructure is ready. You can become a bottleneck when your need for precision exceeds what the pace of the work allows. You can also over-engineer solutions, building more system than the problem requires, which creates complexity others must navigate even when your intentions were to reduce it.`,
    needFromTeam: `A WHY partner who keeps the destination honest and helps you connect your operational excellence to outcomes that actually matter. A WHAT partner who ensures the systems you build are actually deployed and not refined indefinitely. Both partners are essential — the WHY keeps you pointed right, the WHAT keeps you moving.`,
    howToWorkWithYou: `Bring them in early on implementation, not after the vision is set. When you need them to adapt a system, show them specifically what's not working and why — don't ask them to accept that change is needed in the abstract. Respect and publicly recognize the operational work they do; it is often invisible to leadership and central to everything.`,
    valueAreas: [
      'Designing and documenting end-to-end operational processes',
      'Identifying and resolving process bottlenecks',
      'Building organizational structures and operating models',
      'Managing multi-workstream programs with many interdependencies',
      'Creating SOPs, playbooks, and operational documentation',
      'Ensuring quality and consistency across complex programs',
      'Implementing technology systems and managing change',
      'Designing reporting structures and accountability frameworks',
      'Conducting organizational assessments and gap analyses',
      'Facilitating working sessions to align teams on process',
    ],
    partners: [
      { type: 'WHY-WHAT or WHY-HOW', reason: 'To provide directional clarity and ensure operational systems serve the right strategic goals' },
      { type: 'WHAT-WHY', reason: 'To inject energy, drive decisions, and keep the team moving while systems are being designed' },
    ],
    areasToWatch: [
      'Can over-engineer solutions, building more system than is needed',
      'May struggle with ambiguity and need more structure than is available',
      'Risk of being so focused on process that innovation is stifled',
      'May not naturally communicate the why behind the systems they build',
      'Can become a bottleneck if they need to control too much',
      'Friction with WHY types who resist structure before vision is set',
    ],
    roles: [
      'Chief Operating Officer',
      'VP of Operations / Head of Operations',
      'Process Engineer / Industrial Engineer',
      'Program Director',
      'IT Systems Manager',
      'Supply Chain Manager',
      'Head of People Operations / HR Operations',
      'Finance Director / CFO',
      'Implementation Consultant',
      'Enterprise Architect',
    ],
  },
};

export default profiles;
